import type { CompanySizeSolutionPage } from "@/types/content";

/**
 * Structural skeleton for the 4 "Solutions by Business Size" pages
 * (`/solutions/{smb,growing-business,mid-market,enterprise}`). Only
 * `id`/`kind` per section lives here — the real translated
 * heading/body/cards/etc. for every section lives in messages/*.json
 * under `companySizeSolutions.<slug>.sections`, matched to this array by
 * index (same convention as src/lib/content/legal.ts). Section count and
 * order MUST match exactly between this file and both message files for
 * a given slug.
 */
export const companySizeSolutionPages: CompanySizeSolutionPage[] = [
  {
    slug: "smb",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "problem", kind: "cardGrid" },
      { id: "solution", kind: "cardGrid" },
      { id: "value-proposition", kind: "arrowChain" },
      { id: "feature-deep-dive-intro", kind: "prose" },
      { id: "feature-crm", kind: "prose" },
      { id: "feature-lead-management", kind: "prose" },
      { id: "feature-sales-pipeline", kind: "prose" },
      { id: "feature-follow-up-automation", kind: "prose" },
      { id: "feature-marketing-automation", kind: "prose" },
      { id: "feature-ai", kind: "prose" },
      { id: "feature-workflow-automation", kind: "arrowChain" },
      { id: "before-after", kind: "beforeAfter" },
      { id: "who-is-it-for", kind: "cardGrid" },
      { id: "use-cases", kind: "cardGrid" },
      { id: "growth", kind: "timeline" },
      { id: "onboarding", kind: "timeline" },
      { id: "management-value", kind: "prose" },
      { id: "team-productivity", kind: "prose" },
      { id: "integrations", kind: "cardGrid" },
      { id: "security", kind: "prose" },
      { id: "roi", kind: "arrowChain" },
      { id: "why-zynreach", kind: "cardGrid" },
      { id: "comparison", kind: "comparisonTable" },
      { id: "faq", kind: "faq" },
    ],
  },
  {
    slug: "growing-business",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "growth-problem", kind: "cardGrid" },
      { id: "core-message", kind: "arrowChain" },
      { id: "before-after", kind: "beforeAfter" },
      { id: "platform-overview", kind: "cardGrid" },
      { id: "unified-customer-management", kind: "prose" },
      { id: "sales-revenue-operations", kind: "prose" },
      { id: "cross-department-collaboration", kind: "arrowChain" },
      { id: "workflow-automation", kind: "arrowChain" },
      { id: "employee-onboarding", kind: "prose" },
      { id: "management-executive-visibility", kind: "cardGrid" },
      { id: "business-intelligence", kind: "arrowChain" },
      { id: "ai-for-growing-businesses", kind: "prose" },
      { id: "multi-team-management", kind: "prose" },
      { id: "multi-branch-ready", kind: "prose" },
      { id: "standardization", kind: "prose" },
      { id: "security-governance", kind: "prose" },
      { id: "integrations", kind: "cardGrid" },
      { id: "scaling-journey", kind: "timeline" },
      { id: "business-maturity", kind: "timeline" },
      { id: "roi", kind: "cardGrid" },
      { id: "why-zynreach", kind: "cardGrid" },
      { id: "comparison", kind: "comparisonTable" },
      { id: "faq", kind: "faq" },
    ],
  },
  {
    slug: "mid-market",
    primaryCtaHref: "/demo",
    secondaryCtaHref: "/contact",
    sections: [
      { id: "inflection-point", kind: "prose" },
      { id: "real-problem", kind: "cardGrid" },
      { id: "value-proposition", kind: "arrowChain" },
      { id: "org-structure", kind: "prose" },
      { id: "governance", kind: "prose" },
      { id: "role-based-access", kind: "cardGrid" },
      { id: "cross-department-workflows", kind: "arrowChain" },
      { id: "approval-workflows", kind: "arrowChain" },
      { id: "process-standardization", kind: "prose" },
      { id: "unified-data-model", kind: "prose" },
      { id: "executive-visibility", kind: "cardGrid" },
      { id: "business-intelligence", kind: "arrowChain" },
      { id: "ai-mid-market", kind: "cardGrid" },
      { id: "automation-center", kind: "arrowChain" },
      { id: "multi-branch", kind: "cardGrid" },
      { id: "territory-assignment", kind: "prose" },
      { id: "customer-360", kind: "cardGrid" },
      { id: "operational-control", kind: "prose" },
      { id: "audit-accountability", kind: "prose" },
      { id: "integrations", kind: "arrowChain" },
      { id: "migration-strategy", kind: "timeline" },
      { id: "deployment-philosophy", kind: "prose" },
      { id: "department-by-department", kind: "cardGrid" },
      { id: "business-maturity", kind: "timeline" },
      { id: "why-zynreach", kind: "cardGrid" },
      { id: "comparison", kind: "comparisonTable" },
      { id: "transformation", kind: "beforeAfter" },
      { id: "executive-roi", kind: "cardGrid" },
      { id: "faq", kind: "faq" },
    ],
  },
  {
    slug: "enterprise",
    primaryCtaHref: "/demo",
    secondaryCtaHref: "/contact",
    sections: [
      { id: "enterprise-reality", kind: "prose" },
      { id: "legacy-problem", kind: "prose" },
      { id: "legacy-problem-model", kind: "arrowChain" },
      { id: "enterprise-value-proposition", kind: "cardGrid" },
      { id: "global-organization-management", kind: "prose" },
      { id: "multi-region-operations", kind: "prose" },
      { id: "multi-branch-governance", kind: "prose" },
      { id: "centralized-identity-access", kind: "prose" },
      { id: "enterprise-security", kind: "prose" },
      { id: "audit-accountability", kind: "prose" },
      { id: "compliance-foundation", kind: "prose" },
      { id: "enterprise-workflow-automation", kind: "arrowChain" },
      { id: "enterprise-approval-engine", kind: "arrowChain" },
      { id: "one-system-of-record", kind: "prose" },
      { id: "customer-360-enterprise", kind: "cardGrid" },
      { id: "revenue-operations", kind: "arrowChain" },
      { id: "ai-at-enterprise-scale", kind: "cardGrid" },
      { id: "ai-governance", kind: "prose" },
      { id: "executive-intelligence", kind: "cardGrid" },
      { id: "enterprise-business-intelligence", kind: "arrowChain" },
      { id: "enterprise-reporting", kind: "cardGrid" },
      { id: "legacy-system-integration", kind: "arrowChain" },
      { id: "enterprise-migration-strategy", kind: "timeline" },
      { id: "enterprise-standardization", kind: "prose" },
      { id: "business-units", kind: "prose" },
      { id: "enterprise-operations", kind: "prose" },
      { id: "enterprise-customer-portal", kind: "prose" },
      { id: "enterprise-document-management", kind: "arrowChain" },
      { id: "scalability", kind: "prose" },
      { id: "enterprise-transformation", kind: "beforeAfter" },
      { id: "enterprise-operating-model", kind: "arrowChain" },
      { id: "why-zynreach-enterprise", kind: "cardGrid" },
      { id: "legacy-stack-comparison", kind: "comparisonTable" },
      { id: "security-governance-promise", kind: "prose" },
      { id: "enterprise-implementation", kind: "cardGrid" },
      { id: "enterprise-adoption-journey", kind: "timeline" },
      { id: "enterprise-roi", kind: "cardGrid" },
      { id: "faq", kind: "faq" },
    ],
  },
];
