import type { LegalPageContent } from "@/types/content";

/**
 * Legal page content (SRS Section 7.20). Effective date and version are
 * modeled as CMS-managed fields (per SRS: "so Legal & Compliance can
 * publish updates without an engineering release") — hardcoded here until
 * the CMS is wired up, per the static-content-first scope decision.
 * General template structure; final language requires Legal sign-off
 * before production use.
 */
export const legalPages: LegalPageContent[] = [
  {
    slug: "privacy",
    navLabel: "Privacy Policy",
    title: "Privacy Policy & Data Protection Notice",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction", heading: "1. Introduction", body: [] },
      { id: "responsible-entity", heading: "2. The Entity Responsible for Processing", body: [] },
      { id: "scope", heading: "3. Scope of This Policy", body: [], list: [] },
      { id: "account-organization-data", heading: "4. Account & Organization Data", body: [] },
      { id: "user-entered-data", heading: "5. Data Entered by the User & Customer Responsibility", body: [] },
      { id: "processor-controller", heading: "6. ZynReach as Processor and as Controller", body: [] },
      { id: "automatic-usage-data", heading: "7. Automatically Collected Data, Usage Data & Audit Logs", body: [] },
      { id: "business-data", heading: "8. Business Data & Lead Generation", body: [] },
      { id: "purposes", heading: "9. Purposes of Processing", body: [], list: [] },
      { id: "legal-basis", heading: "10. Legal Basis for Processing", body: [] },
      { id: "marketing-communications", heading: "11. Marketing Communications", body: [] },
      { id: "cookies", heading: "12. Cookies", body: [], list: [] },
      { id: "data-sharing", heading: "13. Data Sharing & Sub-processors", body: [] },
      { id: "legal-disclosure", heading: "14. Legal Disclosure & Business Transfers", body: [] },
      { id: "data-protection", heading: "15. Data Protection & Shared Security Responsibility", body: [] },
      { id: "data-retention", heading: "16. Data Retention & Deletion", body: [] },
      { id: "children-sensitive-data", heading: "17. Children's Data & Sensitive Data", body: [] },
      { id: "ai-and-data", heading: "18. Artificial Intelligence & Data", body: [] },
      { id: "your-rights", heading: "19. Data Subject Rights", body: [], list: [] },
      { id: "exercising-rights", heading: "20. How to Exercise Your Rights", body: [] },
      { id: "regulatory-international", heading: "21. Regulatory Requests & International Transfers", body: [] },
      { id: "service-providers", heading: "22. Service Providers, Payment Data & Support", body: [] },
      { id: "analytics-links", heading: "23. Analytics & Third-Party Links", body: [] },
      { id: "security-incidents", heading: "24. Security Incidents & Data Breaches", body: [] },
      { id: "changes", heading: "25. Changes to This Policy", body: [] },
      { id: "relationship-to-other-documents", heading: "26. Relationship to Other Documents", body: [] },
      { id: "regulatory-compliance", heading: "27. Regulatory Compliance (GDPR & CCPA)", body: [] },
      { id: "legal-disclaimer", heading: "28. Legal Disclaimer", body: [] },
      { id: "contact", heading: "29. Contact Us", body: [] },
    ],
  },
  {
    slug: "terms",
    navLabel: "Terms & Conditions",
    title: "Terms of Service",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction", heading: "1. Introduction", body: [] },
      { id: "definitions", heading: "2. Definitions", body: [], list: [] },
      { id: "acceptance-eligibility", heading: "3. Acceptance of Terms & Eligibility", body: [] },
      { id: "account-registration", heading: "4. Account Registration & Responsibility", body: [] },
      { id: "provision-modification", heading: "5. Provision & Modification of Services", body: [] },
      { id: "free-trials", heading: "6. Free Trials, Demos & Free Plans", body: [] },
      { id: "paid-subscriptions", heading: "7. Paid Subscriptions & Pricing", body: [] },
      { id: "billing-taxes", heading: "8. Billing & Taxes", body: [] },
      { id: "late-payment", heading: "9. Late Payment", body: [] },
      { id: "renewal-cancellation", heading: "10. Renewal & Cancellation", body: [] },
      { id: "refunds", heading: "11. Refunds", body: [] },
      { id: "suspension", heading: "12. Suspension of Service", body: [], list: [] },
      { id: "ownership", heading: "13. ZynReach's Ownership & Intellectual Property", body: [] },
      { id: "license-restrictions", heading: "14. License to Use the Services & Restrictions", body: [] },
      { id: "customer-data", heading: "15. Customer Data & Customer Responsibility", body: [] },
      { id: "privacy-dpa-security", heading: "16. Privacy, Data Processing Agreement & Security", body: [] },
      { id: "third-party-services", heading: "17. Third-Party & External Services", body: [] },
      { id: "ai-features", heading: "18. Artificial Intelligence Features", body: [] },
      { id: "feedback", heading: "19. Feedback", body: [] },
      { id: "confidentiality", heading: "20. Confidentiality", body: [] },
      { id: "compliance-regulated", heading: "21. Compliance with Laws & Regulated Industries", body: [] },
      { id: "acceptable-use", heading: "22. Acceptable Use & Customer Security Responsibilities", body: [] },
      { id: "support-slas", heading: "23. Support, Service Levels, Maintenance & Beta Features", body: [] },
      { id: "content-backups", heading: "24. Content Monitoring & Backups", body: [] },
      { id: "termination", heading: "25. Termination & Effect of Termination", body: [] },
      { id: "disclaimers", heading: "26. Disclaimer of Warranties", body: [] },
      { id: "limitation-of-liability", heading: "27. Limitation of Liability", body: [] },
      { id: "indemnification", heading: "28. Indemnification", body: [] },
      { id: "force-majeure", heading: "29. Force Majeure", body: [] },
      { id: "notices-amendments", heading: "30. Notices & Amendments to These Terms", body: [] },
      { id: "general-provisions", heading: "31. General Legal Provisions", body: [] },
      { id: "governing-law", heading: "32. Governing Law & Dispute Resolution", body: [] },
      { id: "enterprise-government", heading: "33. Enterprise & Government Customers", body: [] },
      { id: "export-controls", heading: "34. Export Controls, Anti-Corruption & Platform Integrity", body: [] },
      { id: "apis-integrations", heading: "35. APIs, Integrations & Related Policies", body: [] },
      { id: "contact", heading: "36. Contact & Acknowledgment", body: [] },
    ],
  },
  {
    slug: "data-retention",
    navLabel: "Data Retention & Deletion",
    title: "Data Retention & Deletion Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of the Policy", body: [] },
      { id: "scope", heading: "2. Scope of Application", body: [] },
      { id: "core-principles", heading: "3. Core Principles of Data Retention", body: [], list: [] },
      { id: "categories-of-data", heading: "4. Categories of Data", body: [], list: [] },
      { id: "retention-schedule", heading: "5. Data Retention Schedule", body: [], list: [] },
      { id: "customer-data-responsibility", heading: "6. Customer Data & Retention Responsibility", body: [] },
      { id: "end-of-subscription", heading: "7. End of Customer Subscription & Data Deletion", body: [] },
      { id: "backups", heading: "8. Backups", body: [] },
      { id: "secure-deletion", heading: "9. Secure Deletion & Anonymization", body: [] },
      { id: "legal-hold", heading: "10. Legally Required Data & Legal Hold", body: [] },
      { id: "individual-requests", heading: "11. Individual Deletion Requests", body: [] },
      { id: "account-inactive", heading: "12. Account Data & Inactive Accounts", body: [] },
      { id: "marketing-correspondence", heading: "13. Marketing Data & Correspondence", body: [] },
      { id: "system-security-logs", heading: "14. System, Security & Audit Logs", body: [] },
      { id: "sub-processors", heading: "15. Sub-processors & Independent Third Parties", body: [] },
      { id: "lifecycle-classification", heading: "16. Data Lifecycle & Classification", body: [] },
      { id: "minimum-retention", heading: "17. Minimum Retention & Periodic Review", body: [] },
      { id: "internal-access", heading: "18. Internal Access & Termination of Access", body: [] },
      { id: "temporary-cached", heading: "19. Temporary & Cached Data, and Technical Logs", body: [] },
      { id: "multi-phase-deletion", heading: "20. Multi-Phase Deletion at Service Termination & Exceptions", body: [], list: [] },
      { id: "technical-limitations", heading: "21. Technical Limitations & No Guarantee of Immediate Deletion", body: [] },
      { id: "proof-of-deletion", heading: "22. Proof of Deletion & Customer Requests", body: [] },
      { id: "relationship-to-other-policies", heading: "23. Relationship to Other Policies", body: [] },
      { id: "compliance-changes", heading: "24. Compliance & Changes to This Policy", body: [] },
      { id: "precedence-contact", heading: "25. Order of Precedence & Contact", body: [] },
      { id: "legal-notice", heading: "26. Legal Notice", body: [] },
    ],
  },
  {
    slug: "acceptable-use",
    navLabel: "Acceptable Use",
    title: "Acceptable Use Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of the Policy", body: [] },
      { id: "scope-definitions", heading: "2. Scope of Application & Definition of Services", body: [] },
      { id: "permitted-use", heading: "3. Permitted Use & Compliance with Laws", body: [] },
      { id: "hacking-access", heading: "4. Hacking, Cyberattacks & Unauthorized Account Access", body: [] },
      { id: "malware", heading: "5. Malware", body: [] },
      { id: "phishing-fraud", heading: "6. Phishing, Fraud & Impersonation", body: [] },
      { id: "spam", heading: "7. Spam & Unsolicited Messages", body: [] },
      { id: "resource-abuse", heading: "8. Resource Abuse, Rate Limits & Denial-of-Service", body: [] },
      { id: "security-scanning", heading: "9. Security Scanning & Penetration Testing", body: [] },
      { id: "unlawful-data-collection", heading: "10. Unlawful Data Collection & Sensitive Data", body: [] },
      { id: "unlawful-content-ip", heading: "11. Unlawful Content & Intellectual Property", body: [] },
      { id: "privacy-financial", heading: "12. Privacy Violations & Financial Information", body: [] },
      { id: "harmful-content", heading: "13. Harmful Content & High-Risk Uses", body: [] },
      { id: "ai", heading: "14. Artificial Intelligence", body: [] },
      { id: "automation-scraping", heading: "15. Automation, Web Scraping & Trial Accounts", body: [] },
      { id: "login-credentials", heading: "16. Login Credentials & Customer Responsibility for Users", body: [] },
      { id: "user-content", heading: "17. User-Submitted Content & No Implied Consent", body: [] },
      { id: "monitoring-investigation", heading: "18. Security Monitoring & Investigation of Violations", body: [] },
      { id: "suspension-emergency", heading: "19. Suspension of Accounts & Emergency Action", body: [] },
      { id: "content-removal", heading: "20. Content Removal & Government Requests", body: [] },
      { id: "reporting-abuse", heading: "21. Reporting Abuse & False Reports", body: [] },
      { id: "vulnerability-reporting", heading: "22. Vulnerability Reporting", body: [] },
      { id: "relationship-to-other-policies", heading: "23. Relationship to Other Policies", body: [] },
      { id: "enforcement-actions", heading: "24. Enforcement Actions & Factors Considered", body: [], list: [] },
      { id: "service-restoration", heading: "25. Service Restoration & Third-Party Responsibility", body: [] },
      { id: "commercial-restrictions", heading: "26. Commercial Restrictions, Resale & Trademark Use", body: [] },
      { id: "liability-limits", heading: "27. Limits of ZynReach's Liability", body: [] },
      { id: "amendments", heading: "28. Amendments to This Policy & Their Effect", body: [] },
      { id: "precedence-severability", heading: "29. Order of Precedence, Severability & No Waiver", body: [] },
      { id: "contact", heading: "30. Contact & Legal Notice", body: [] },
    ],
  },
  {
    slug: "security-trust-policy",
    navLabel: "Security & Trust",
    title: "Security & Trust Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction", heading: "1. Introduction", body: [] },
      { id: "purpose", heading: "2. Purpose of the Policy", body: [] },
      { id: "scope", heading: "3. Scope of the Policy", body: [] },
      { id: "principles", heading: "4. Security & Trust Principles", body: [], list: [] },
      { id: "classification", heading: "5. Information Classification", body: [] },
      { id: "customer-data-protection", heading: "6. Protection of Customer Data", body: [] },
      { id: "encryption", heading: "7. Encryption", body: [] },
      { id: "identity-access", heading: "8. Identity & Access Management", body: [] },
      { id: "mfa", heading: "9. Multi-Factor Authentication", body: [] },
      { id: "privilege-management", heading: "10. Privilege Management & Administrative Access", body: [] },
      { id: "audit-logging", heading: "11. Audit Logging & Log Integrity", body: [] },
      { id: "secure-development", heading: "12. Secure Software Development", body: [] },
      { id: "vulnerability-management", heading: "13. Vulnerability Management", body: [] },
      { id: "security-testing", heading: "14. Security Testing", body: [] },
      { id: "security-monitoring", heading: "15. Security Monitoring", body: [] },
      { id: "incident-management", heading: "16. Security Incident Management", body: [] },
      { id: "customer-notification", heading: "17. Customer Incident Notification", body: [] },
      { id: "backup-dr-bc", heading: "18. Backup, Disaster Recovery & Business Continuity", body: [] },
      { id: "infrastructure-security", heading: "19. Infrastructure Security", body: [] },
      { id: "sub-processors-vendor-risk", heading: "20. Sub-processors & Vendor Risk Management", body: [] },
      { id: "data-protection-minimization", heading: "21. Data Protection, Privacy & Data Minimization", body: [] },
      { id: "retention-transfers", heading: "22. Data Retention & International Transfers", body: [] },
      { id: "personnel-security", heading: "23. Personnel Security & Access Termination", body: [] },
      { id: "integration-api-ai-security", heading: "24. Integration, API & AI Security", body: [] },
      { id: "shared-responsibility", heading: "25. Shared Responsibility Model", body: [] },
      { id: "vulnerability-disclosure", heading: "26. Vulnerability Disclosure & Unauthorized Testing", body: [] },
      { id: "compliance-frameworks", heading: "27. Compliance & Security Frameworks", body: [] },
      { id: "security-documentation", heading: "28. Security Documentation & Confidentiality", body: [] },
      { id: "no-absolute-guarantee", heading: "29. No Absolute Security Guarantee & Limitation of Liability", body: [] },
      { id: "amendments-relationship", heading: "30. Amendments & Relationship to Other Documents", body: [] },
      { id: "intellectual-property", heading: "31. Intellectual Property", body: [] },
      { id: "contact", heading: "32. Contact & Security Notification", body: [] },
      { id: "commitment-to-trust", heading: "33. Our Commitment to Trust", body: [] },
      { id: "legal-disclaimer", heading: "34. Legal Disclaimer", body: [] },
    ],
  },
  {
    slug: "incident-response",
    navLabel: "Incident Response",
    title: "Incident Response & Security Breach Notification Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of the Policy", body: [] },
      { id: "scope", heading: "2. Scope of the Policy", body: [] },
      { id: "definitions", heading: "3. Definitions", body: [], list: [] },
      { id: "principles", heading: "4. Core Incident Response Principles", body: [], list: [] },
      { id: "lifecycle", heading: "5. Incident Response Lifecycle", body: [] },
      { id: "detection-reporting", heading: "6. Detecting & Reporting Incidents", body: [] },
      { id: "initial-assessment", heading: "7. Initial Incident Assessment", body: [] },
      { id: "classification", heading: "8. Incident Severity Classification", body: [], list: [] },
      { id: "team-authority", heading: "9. Incident Response Team & Authority", body: [] },
      { id: "containment-investigation", heading: "10. Containment & Technical Investigation", body: [] },
      { id: "evidence-eradication", heading: "11. Preservation of Evidence & Eradication", body: [] },
      { id: "service-restoration", heading: "12. Service Restoration", body: [] },
      { id: "breach-assessment", heading: "13. Assessing Whether an Incident Is a Data Breach", body: [] },
      { id: "customer-notification", heading: "14. Customer Notification & Phased Notification", body: [] },
      { id: "notification-content-timing", heading: "15. Notification Content & Timing", body: [] },
      { id: "notification-on-behalf", heading: "16. Notification on Behalf of the Customer & Regulatory Notification", body: [] },
      { id: "public-communications", heading: "17. Public Communications & Investigation Confidentiality", body: [] },
      { id: "sub-processor-incidents", heading: "18. Incidents at Sub-processors", body: [] },
      { id: "account-incidents", heading: "19. Account-Related Incidents & Customer Responsibility", body: [] },
      { id: "cooperation-cost", heading: "20. Cooperation with the Customer & Cost of Response", body: [] },
      { id: "external-experts", heading: "21. External Experts & Law Enforcement", body: [] },
      { id: "damage-assessment", heading: "22. Damage Assessment & Corrective Actions", body: [] },
      { id: "post-incident-review", heading: "23. Post-Incident Review & Records", body: [] },
      { id: "testing-bcdr", heading: "24. Testing the Response Plan & Relationship to Business Continuity", body: [] },
      { id: "limits-no-admission", heading: "25. Limits of Commitment & No Admission of Liability", body: [] },
      { id: "sensitive-info-vulnerabilities", heading: "26. Protecting Sensitive Information & Handling Vulnerabilities", body: [] },
      { id: "responsible-disclosure", heading: "27. Responsible Disclosure & Staff Obligations", body: [] },
      { id: "policy-review", heading: "28. Policy Review & Amendments", body: [] },
      { id: "precedence-contact", heading: "29. Order of Precedence & Incident Contact", body: [] },
      { id: "legal-notice", heading: "30. Legal Notice", body: [] },
    ],
  },
  {
    slug: "vulnerability-disclosure",
    navLabel: "Vulnerability Disclosure",
    title: "Vulnerability Disclosure Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [] },
      { id: "scope-out-of-scope", heading: "2. Scope of the Policy & Out-of-Scope Assets", body: [] },
      { id: "testing-purpose-definition", heading: "3. Purpose of Testing & Definition of a Vulnerability", body: [] },
      { id: "responsible-disclosure-channel", heading: "4. Responsible Disclosure & Reporting Channel", body: [] },
      { id: "report-info-evidence", heading: "5. Report Information & Minimum Evidence", body: [] },
      { id: "data-encountered", heading: "6. Data Encountered During Testing", body: [] },
      { id: "no-data-modification", heading: "7. Prohibition on Data Modification & Service Disruption", body: [] },
      { id: "no-malware-exploitation", heading: "8. Prohibition on Malware & Post-Proof Exploitation", body: [] },
      { id: "account-takeover-auth-testing", heading: "9. Account Takeover & Authentication/Authorization Testing", body: [] },
      { id: "automated-scanning", heading: "10. Automated Scanning & Rate Limits", body: [] },
      { id: "out-of-scope-testing", heading: "11. Out-of-Scope Testing Types", body: [] },
      { id: "third-party-shared-vulnerabilities", heading: "12. Third-Party & Shared Vulnerabilities", body: [] },
      { id: "safe-harbor-good-faith", heading: "13. Safe Harbor & Good Faith", body: [] },
      { id: "do-no-harm", heading: "14. Do No Harm & Stopping Tests", body: [] },
      { id: "cleanup-no-retention", heading: "15. Cleanup & No Data Retention", body: [] },
      { id: "poc-standards", heading: "16. Proof of Concept Standards", body: [] },
      { id: "severity-classification", heading: "17. Severity Classification & Final Determination", body: [] },
      { id: "report-verification", heading: "18. Report Verification & Researcher Communication", body: [] },
      { id: "response-time", heading: "19. Response Time & Vulnerability Verification", body: [] },
      { id: "false-positives-duplicates", heading: "20. False Positives & Duplicate Reports", body: [] },
      { id: "non-qualifying-reports", heading: "21. Non-Qualifying Reports", body: [], list: [] },
      { id: "confidentiality-privacy", heading: "22. Confidentiality & Privacy", body: [] },
      { id: "public-coordinated-disclosure", heading: "23. Public & Coordinated Disclosure", body: [] },
      { id: "researcher-recognition", heading: "24. Researcher Recognition & Compensation", body: [] },
      { id: "no-employment-ownership", heading: "25. No Employment Relationship, Ownership Rights & Trademark Use", body: [] },
      { id: "policy-abuse-extortion", heading: "26. Policy Abuse & Extortion", body: [] },
      { id: "safe-harbor-limitations", heading: "27. Safe Harbor Limitations", body: [] },
      { id: "scope-changes-emergency", heading: "28. Scope Changes & Emergency Security Actions", body: [] },
      { id: "responsibilities", heading: "29. Researcher & ZynReach Responsibilities", body: [] },
      { id: "remediation-advisories", heading: "30. Remediation Process & Security Advisories", body: [] },
      { id: "general-provisions", heading: "31. General Provisions", body: [] },
      { id: "contact-authority", heading: "32. Contact & Final Authority", body: [] },
      { id: "legal-notice", heading: "33. Legal Notice", body: [] },
    ],
  },
  {
    slug: "business-continuity",
    navLabel: "Business Continuity & Disaster Recovery",
    title: "Business Continuity & Disaster Recovery Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [] },
      { id: "scope", heading: "2. Scope of the Policy", body: [] },
      { id: "objectives", heading: "3. Continuity Objectives", body: [], list: [] },
      { id: "principles", heading: "4. BCDR Principles", body: [], list: [] },
      { id: "disaster-definition", heading: "5. Definition of a Disaster", body: [] },
      { id: "bc-dr-definitions", heading: "6. Business Continuity & Disaster Recovery", body: [] },
      { id: "bia-classification", heading: "7. Business Impact Analysis & System Classification", body: [] },
      { id: "recovery-prioritization", heading: "8. Recovery Prioritization", body: [] },
      { id: "rto-rpo", heading: "9. Recovery Time & Point Objectives (RTO/RPO)", body: [] },
      { id: "bc-dr-plans", heading: "10. Business Continuity & Disaster Recovery Plans", body: [] },
      { id: "dr-architecture", heading: "11. Disaster Recovery Architecture & External Dependencies", body: [] },
      { id: "backups", heading: "12. Backups & Their Protection", body: [] },
      { id: "database-recovery", heading: "13. Database Recovery, Data Integrity & Failover/Failback", body: [] },
      { id: "crisis-management", heading: "14. Crisis Management & Incident Commander", body: [] },
      { id: "severity-escalation", heading: "15. Incident Severity & Escalation", body: [] },
      { id: "communication", heading: "16. Communication During Disasters", body: [] },
      { id: "cyber-dr", heading: "17. Cyber Disaster Recovery & Ransomware Response", body: [] },
      { id: "recovery-validation", heading: "18. Recovery Validation & Post-Recovery Monitoring", body: [] },
      { id: "essential-personnel", heading: "19. Essential Personnel & Role Redundancy", body: [] },
      { id: "asset-documentation", heading: "20. Asset & Recovery Procedure Documentation", body: [] },
      { id: "change-management", heading: "21. Change Management During Disasters", body: [] },
      { id: "testing-program", heading: "22. Testing Program", body: [] },
      { id: "lessons-learned", heading: "23. Lessons Learned, Corrective Actions & Policy Review", body: [] },
      { id: "vendor-risk", heading: "24. Vendor Risk & Dependency on External Services", body: [] },
      { id: "security-during-recovery", heading: "25. Data Security During Recovery", body: [] },
      { id: "dr-documentation", heading: "26. Disaster Recovery Documentation", body: [] },
      { id: "governance-roles", heading: "27. Governance & Roles", body: [] },
      { id: "customer-responsibility", heading: "28. Customer Responsibility & Shared Responsibility", body: [] },
      { id: "enterprise-disclosure", heading: "29. Disclosure to Enterprise Customers", body: [] },
      { id: "sla-relationship", heading: "30. Relationship to the SLA & Other Documents", body: [] },
      { id: "disclaimers", heading: "31. Availability & No-Data-Loss Disclaimers", body: [] },
      { id: "confidentiality-exceptions", heading: "32. Confidentiality, Exceptions & Violations", body: [] },
      { id: "continuous-improvement", heading: "33. Continuous Improvement & Periodic Review", body: [] },
      { id: "legal-notice", heading: "34. Legal Notice", body: [] },
    ],
  },
  {
    slug: "enterprise-security-addendum",
    navLabel: "Enterprise Security Addendum",
    title: "Enterprise Security Addendum",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [] },
      { id: "scope", heading: "2. Scope of Application", body: [] },
      { id: "definitions", heading: "3. Definitions", body: [], list: [] },
      { id: "security-framework", heading: "4. Security Framework & Information Security Management Program", body: [] },
      { id: "management-responsibility", heading: "5. Management Responsibility & Risk Assessment", body: [] },
      { id: "policy-personnel-training", heading: "6. Policy Management, Personnel Security & Training", body: [] },
      { id: "access-mfa", heading: "7. Access Management, Role-Based Access Control & Multi-Factor Authentication", body: [] },
      { id: "permission-review", heading: "8. Permission Review, Access Termination & Administrative Accounts", body: [] },
      { id: "credential-encryption", heading: "9. Credential Protection & Encryption", body: [] },
      { id: "isolation", heading: "10. Customer Data Isolation & Isolation Testing", body: [] },
      { id: "secure-development", heading: "11. Secure Software Development & Application Security", body: [] },
      { id: "vulnerability-testing-disclosure", heading: "12. Vulnerability Management, Security Testing & Responsible Disclosure", body: [] },
      { id: "logging-monitoring", heading: "13. Logging & Monitoring", body: [] },
      { id: "incident-management", heading: "14. Incident Management & Notification", body: [] },
      { id: "incident-cooperation", heading: "15. Incident Cooperation & Communication", body: [] },
      { id: "bcdr", heading: "16. Business Continuity & Disaster Recovery", body: [] },
      { id: "change-management", heading: "17. Change Management", body: [] },
      { id: "infrastructure-security", heading: "18. Infrastructure, Cloud, Network & Endpoint Security", body: [] },
      { id: "vendor-security", heading: "19. Vendor & Sub-processor Security", body: [] },
      { id: "retention-deletion", heading: "20. Data Retention, Deletion & Minimization", body: [] },
      { id: "customer-responsibilities", heading: "21. Customer Security Responsibilities & Shared Responsibility Model", body: [] },
      { id: "api-security", heading: "22. API Security & Third-Party Integrations", body: [] },
      { id: "security-documentation", heading: "23. Security Documentation & Independent Audit Reports", body: [] },
      { id: "audit-rights", heading: "24. Customer Audit Rights & Alternatives", body: [] },
      { id: "customer-testing", heading: "25. Customer-Conducted Testing & Vulnerability Reporting", body: [] },
      { id: "record-management", heading: "26. Record Management, Access Monitoring & No Absolute Security Guarantee", body: [] },
      { id: "compliance-relationship", heading: "27. Compliance & Relationship to Other Documents", body: [] },
      { id: "security-contact", heading: "28. Security Contact & Handling of Incident Information", body: [] },
      { id: "data-location", heading: "29. Data Location, Security Changes & Exceptions", body: [] },
      { id: "recovery-objectives", heading: "30. Recovery Objectives, Addendum Review & Amendments", body: [] },
      { id: "precedence-liability", heading: "31. Precedence, Liability, Confidentiality & Additional Addenda", body: [] },
      { id: "shared-responsibility", heading: "32. Shared Responsibility, General Provisions & Legal Notice", body: [] },
    ],
  },
  {
    slug: "data-transfer",
    navLabel: "International Data Transfer",
    title: "Data Transfer & International Data Transfer Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [] },
      { id: "scope", heading: "2. Scope of the Policy", body: [] },
      { id: "definitions", heading: "3. Definition of Data & Data Transfer", body: [] },
      { id: "transfer-principles", heading: "4. Data Transfer Principles", body: [] },
      { id: "no-fixed-location", heading: "5. No Guarantee of a Fixed Data Location", body: [] },
      { id: "data-residency", heading: "6. Data Residency & Regional Hosting", body: [] },
      { id: "lawful-basis", heading: "7. Lawful Basis for Transfer", body: [] },
      { id: "sccs-tia", heading: "8. Standard Contractual Clauses & Transfer Impact Assessment", body: [] },
      { id: "supplementary-measures", heading: "9. Supplementary Measures & Encryption", body: [] },
      { id: "access-control", heading: "10. Access Control, Authentication, Logging & Monitoring", body: [] },
      { id: "sub-processors", heading: "11. Sub-processors & International Transfer", body: [] },
      { id: "government-requests", heading: "12. Government Requests & Legal Review", body: [] },
      { id: "intra-group", heading: "13. Intra-Group Transfers & Internal Cross-Border Access", body: [] },
      { id: "customer-export", heading: "14. Customer Data Export & Customer-Initiated Transfers", body: [] },
      { id: "transit-rest", heading: "15. Data Protection in Transit & At Rest", body: [] },
      { id: "backup-dr", heading: "16. Backup & Disaster Recovery Transfers", body: [] },
      { id: "sensitive-data", heading: "17. Sensitive Data & Special Categories", body: [] },
      { id: "customer-responsibility", heading: "18. Customer Responsibility & Controller/Processor Roles", body: [] },
      { id: "dpa-priority", heading: "19. Data Processing Agreement & Its Priority", body: [] },
      { id: "applicable-laws", heading: "20. Applicable Data Protection Laws", body: [] },
      { id: "transfer-mechanisms", heading: "21. Transfer Mechanisms", body: [] },
      { id: "transfer-risk", heading: "22. Transfer Risk & Risk-Based Approach", body: [] },
      { id: "retention-deletion", heading: "23. Retention & Deletion of Transferred Data", body: [] },
      { id: "security-incidents", heading: "24. Security Incidents & Breach Notification", body: [] },
      { id: "documentation-records", heading: "25. Documentation & Records of Processing", body: [] },
      { id: "audits-transparency", heading: "26. Audits & Transparency", body: [] },
      { id: "infrastructure-changes", heading: "27. Infrastructure Changes & Customer Notice", body: [] },
      { id: "employee-access", heading: "28. International Employee Access to Data", body: [] },
      { id: "customer-configuration", heading: "29. Customer Configuration & International Customers", body: [] },
      { id: "restricted-jurisdictions", heading: "30. Restricted Jurisdictions & Sanctions/Export Controls", body: [] },
      { id: "policy-changes", heading: "31. Policy Changes, Relationship to Other Documents & Order of Precedence", body: [] },
      { id: "disclaimers", heading: "32. Disclaimers, Compliance & Contact", body: [] },
    ],
  },
  {
    slug: "sub-processor-policy",
    navLabel: "Sub-processor Policy",
    title: "Sub-processor Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction", heading: "1. Introduction", body: [] },
      { id: "definitions", heading: "2. Definitions", body: [] },
      { id: "scope", heading: "3. Scope of the Policy", body: [], list: [] },
      { id: "core-principle", heading: "4. Core Principle", body: [] },
      { id: "selection", heading: "5. Selection of Sub-processors", body: [], list: [] },
      { id: "contractual-requirements", heading: "6. Contractual Requirements", body: [], list: [] },
      { id: "sub-processor-list", heading: "7. Sub-processor List", body: [] },
      { id: "adding-replacing", heading: "8. Adding or Replacing Sub-processors", body: [] },
      { id: "notification-changes", heading: "9. Notification of Changes", body: [] },
      { id: "right-to-object", heading: "10. Right to Object", body: [] },
      { id: "handling-objections", heading: "11. Handling Customer Objections", body: [] },
      { id: "unresolved-objection", heading: "12. If an Objection Cannot Be Resolved", body: [] },
      { id: "security-data-protection", heading: "13. Security & Data Protection", body: [], list: [] },
      { id: "confidentiality", heading: "14. Confidentiality", body: [] },
      { id: "security-incidents", heading: "15. Security Incidents", body: [] },
      { id: "data-subject-requests", heading: "16. Data Subject Requests", body: [] },
      { id: "international-transfer", heading: "17. International Data Transfer", body: [] },
      { id: "government-orders", heading: "18. Government Orders & Legal Requests", body: [] },
      { id: "cloud-infrastructure", heading: "19. Cloud Infrastructure Services", body: [] },
      { id: "ai-providers", heading: "20. AI Providers", body: [] },
      { id: "payment-services", heading: "21. Payment Services", body: [] },
      { id: "support-providers", heading: "22. Support Service Providers", body: [] },
      { id: "independent-processing", heading: "23. Independent Processing by a Service Provider", body: [] },
      { id: "no-sale", heading: "24. No Sale of Customer Data", body: [] },
      { id: "analytics-use", heading: "25. Use of Data for Analytics Purposes", body: [] },
      { id: "retention-deletion", heading: "26. Data Retention & Deletion", body: [] },
      { id: "monitoring-reassessment", heading: "27. Monitoring & Re-assessment", body: [] },
      { id: "audits-verification", heading: "28. Audits & Verification", body: [] },
      { id: "zynreach-responsibility", heading: "29. ZynReach's Responsibility", body: [] },
      { id: "no-additional-rights", heading: "30. No Additional Rights Granted", body: [] },
      { id: "amendments", heading: "31. Amendments to This Policy", body: [] },
      { id: "dpa-relationship", heading: "32. Relationship with the Data Processing Agreement", body: [] },
      { id: "governing-law", heading: "33. Governing Law & Jurisdiction", body: [] },
      { id: "contact-acknowledgment", heading: "34. Contact, Acknowledgment & Legal Notice", body: [] },
    ],
  },
  {
    slug: "security-documentation-request",
    navLabel: "Request Security Documentation",
    title: "Security & Compliance Documentation Request Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of This Document", body: [] },
      { id: "scope", heading: "2. Scope of Application", body: [] },
      { id: "document-tiers", heading: "3. Nature of Security & Compliance Documents", body: [], list: [] },
      { id: "non-disclosed-information", heading: "4. Information ZynReach Is Not Obligated to Disclose", body: [], list: [] },
      { id: "no-automatic-disclosure", heading: "5. Security Documents Are Not Automatically Disclosed", body: [], list: [] },
      { id: "identity-verification", heading: "6. Verifying the Requester's Identity", body: [] },
      { id: "business-email", heading: "7. Business/Professional Email", body: [] },
      { id: "nda", heading: "8. Non-Disclosure Agreement (NDA)", body: [] },
      { id: "use-of-documents", heading: "9. Use of Documents", body: [], list: [] },
      { id: "republication-prohibition", heading: "10. Prohibition on Republication", body: [], list: [] },
      { id: "third-party-documents", heading: "11. Third-Party-Issued Documents", body: [] },
      { id: "certifications-frameworks", heading: "12. Certifications, Frameworks & Standards", body: [] },
      { id: "not-legal-advice", heading: "13. Documents Do Not Constitute Legal Advice", body: [] },
      { id: "personal-data-protection", heading: "14. Protection of Personal Data During the Request Process", body: [] },
      { id: "customer-data-processing", heading: "15. Processing of Customer Data", body: [] },
      { id: "sub-processors", heading: "16. Sub-processors", body: [] },
      { id: "international-transfer", heading: "17. International Data Transfer", body: [] },
      { id: "incident-management", heading: "18. Security Incident Management", body: [] },
      { id: "ongoing-security", heading: "19. Security as an Ongoing Process", body: [] },
      { id: "backup-recovery", heading: "20. Backup & Recovery", body: [] },
      { id: "customer-obligations", heading: "21. Customer Obligations", body: [], list: [] },
      { id: "not-a-substitute", heading: "22. ZynReach Is Not a Substitute for Customer Security Responsibilities", body: [] },
      { id: "review-team-obligations", heading: "23. Obligations of the Customer's Review Team", body: [], list: [] },
      { id: "offensive-testing-prohibition", heading: "24. Prohibition on Unauthorized Offensive Testing", body: [] },
      { id: "request-procedure", heading: "25. Document Request Procedure", body: [], list: [] },
      { id: "processing-time", heading: "26. Request Processing Time", body: [] },
      { id: "document-accuracy", heading: "27. Document Accuracy & Currency", body: [] },
      { id: "program-changes", heading: "28. Changes to the Security Program", body: [] },
      { id: "no-additional-guarantees", heading: "29. No Additional Guarantees Created", body: [] },
      { id: "document-conflicts", heading: "30. Conflicts Between Documents", body: [] },
      { id: "intellectual-property", heading: "31. Intellectual Property Rights", body: [] },
      { id: "leaked-documents", heading: "32. Notification of Leaked or Lost Documents", body: [] },
      { id: "amend-withdraw", heading: "33. ZynReach's Right to Amend or Withdraw Documents", body: [] },
      { id: "no-absolute-guarantee", heading: "34. No Absolute Security Guarantee", body: [] },
      { id: "governing-law", heading: "35. Governing Law & Jurisdiction", body: [] },
      { id: "contact-acknowledgment", heading: "36. Contacting the Security & Compliance Team & Requester Acknowledgment", body: [] },
      { id: "disclaimer", heading: "37. Disclaimer", body: [] },
    ],
  },
  {
    slug: "cookies",
    navLabel: "Cookie Policy",
    title: "Cookie Policy",
    effectiveDate: "2026-08-01",
    version: "1.0",
    sections: [
      { id: "what-are-cookies", heading: "1. What Are Cookies", body: ["Cookies are small text files stored on your device that help websites function and remember preferences."] },
      { id: "types-of-cookies", heading: "2. Types of Cookies We Use", body: ["Essential — required for core site functionality; cannot be disabled.", "Analytics — help us understand site usage; only active with your consent.", "Advertising — support marketing measurement; only active with your consent.", "Functional — remember preferences like language; only active with your consent."] },
      { id: "managing-preferences", heading: "3. Managing Your Preferences", body: ["You can accept, reject, or customize non-essential cookies via the cookie banner shown on your first visit, or by clearing your browser's stored consent to see it again."] },
      { id: "third-party-cookies", heading: "4. Third-Party Cookies", body: ["Some cookies are set by third-party analytics and advertising partners. Their use is governed by their own privacy policies."] },
      { id: "changes", heading: "5. Changes to This Policy", body: ["We may update this policy periodically; the effective date above reflects the latest revision."] },
      { id: "contact", heading: "6. Contact Us", body: ["Questions about cookies can be sent to privacy@zynreach.com."] },
    ],
  },
  {
    slug: "dpa",
    navLabel: "Data Processing Agreement",
    title: "Data Processing Agreement",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction-parties", heading: "1. Introduction & Parties", body: [] },
      { id: "purpose-scope", heading: "2. Purpose & Scope", body: [] },
      { id: "definitions", heading: "3. Definitions", body: [], list: [] },
      { id: "relationship-to-master-agreement", heading: "4. Relationship to the Master Agreement", body: [] },
      { id: "roles-of-the-parties", heading: "5. Roles of the Parties", body: [] },
      { id: "customer-obligations", heading: "6. Customer Obligations & Warranties", body: [], list: [] },
      { id: "processing-instructions", heading: "7. Processing Instructions", body: [], list: [] },
      { id: "limits-on-data-use", heading: "8. Limits on Data Use & Aggregated Data", body: [] },
      { id: "categories-of-data", heading: "9. Categories of Personal Data & Data Subjects", body: [], list: [] },
      { id: "special-categories", heading: "10. Special Categories & Children's Data", body: [] },
      { id: "duration-of-processing", heading: "11. Duration of Processing", body: [] },
      { id: "confidentiality-personnel", heading: "12. Confidentiality & Personnel", body: [] },
      { id: "security-measures", heading: "13. Information Security Measures", body: [], list: [] },
      { id: "access-control", heading: "14. Access Control", body: [] },
      { id: "sub-processors", heading: "15. Sub-processors", body: [] },
      { id: "data-subject-requests", heading: "16. Data Subject Requests", body: [] },
      { id: "regulatory-cooperation", heading: "17. Regulatory Cooperation & DPIA Support", body: [] },
      { id: "breach-notification", heading: "18. Personal Data Breach Notification", body: [] },
      { id: "government-requests", heading: "19. Government & Third-Party Requests", body: [] },
      { id: "international-transfers", heading: "20. International Data Transfers", body: [] },
      { id: "audit-rights", heading: "21. Audit Rights", body: [] },
      { id: "record-retention", heading: "22. Record Retention", body: [] },
      { id: "data-return-deletion", heading: "23. Data Return & Deletion", body: [] },
      { id: "ownership", heading: "24. Data & Intellectual Property Ownership", body: [] },
      { id: "ai-processing", heading: "25. Artificial Intelligence Processing", body: [] },
      { id: "integrations-apis", heading: "26. Third-Party Integrations & APIs", body: [] },
      { id: "customer-security-obligations", heading: "27. Customer Security Obligations", body: [] },
      { id: "liability-force-majeure", heading: "28. Liability & Force Majeure", body: [] },
      { id: "term-termination", heading: "29. Term & Termination", body: [] },
      { id: "general-provisions", heading: "30. General Provisions", body: [] },
      { id: "annexes", heading: "31. Annexes", body: [], list: [] },
    ],
  },
];

export function getLegalPage(slug: string) {
  return legalPages.find((page) => page.slug === slug);
}
