import type { LegalPageContent } from "@/types/content";

/**
 * Legal page content (SRS Section 7.20). Effective date and version are
 * modeled as CMS-managed fields (per SRS: "so Legal & Compliance can
 * publish updates without an engineering release") — hardcoded here until
 * the CMS is wired up, per the static-content-first scope decision.
 * General template structure; final language requires Legal sign-off
 * before production use.
 */
export const legalPages: LegalPageContent[] = [
  {
    slug: "privacy",
    navLabel: "Privacy Policy",
    title: "Privacy Policy & Data Protection Notice",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction", heading: "1. Introduction", body: [], list: [] },
      { id: "responsible-party", heading: "2. Data Controller / Responsible Party", body: [], list: [] },
      { id: "scope", heading: "3. Scope of This Policy", body: [], list: [] },
      { id: "data-we-collect", heading: "4. Data We Collect", body: [], list: [] },
      { id: "organization-data", heading: "5. Organization Data", body: [], list: [] },
      { id: "customer-entered-data", heading: "6. Customer Data Entered by Users", body: [], list: [] },
      { id: "customer-responsibility", heading: "7. Customer Responsibility for Data It Enters", body: [], list: [] },
      { id: "data-processor-role", heading: "8. ZynReach as a Data Processor", body: [] },
      { id: "data-controller-role", heading: "9. ZynReach as a Data Controller", body: [], list: [] },
      { id: "automatically-collected-data", heading: "10. Data Collected Automatically", body: [], list: [] },
      { id: "usage-data", heading: "11. Usage Data", body: [], list: [] },
      { id: "audit-logs", heading: "12. Audit Logs", body: [], list: [] },
      { id: "business-data-lead-generation", heading: "13. Business Data and Lead Generation", body: [], list: [] },
      { id: "public-data-not-nonpersonal", heading: "14. Public Availability Does Not Mean \"Non-Personal\"", body: [] },
      { id: "third-party-data-sources", heading: "15. Third-Party Data Sources", body: [] },
      { id: "processing-purposes", heading: "16. Purposes of Data Processing", body: [], list: [] },
      { id: "legal-basis", heading: "17. Legal Basis for Processing", body: [], list: [] },
      { id: "legitimate-interests", heading: "18. Legitimate Interests", body: [], list: [] },
      { id: "consent", heading: "19. Consent", body: [] },
      { id: "marketing-communications", heading: "20. Marketing Communications", body: [], list: [] },
      { id: "marketing-opt-out", heading: "21. Marketing Opt-Out", body: [], list: [] },
      { id: "cookies", heading: "22. Cookies", body: [], list: [] },
      { id: "cookie-management", heading: "23. Cookie Management", body: [] },
      { id: "data-sharing", heading: "24. Data Sharing", body: [], list: [] },
      { id: "sub-processors", heading: "25. Sub-processors", body: [] },
      { id: "legal-disclosure", heading: "26. Disclosure for Legal Reasons", body: [], list: [] },
      { id: "business-transfers", heading: "27. Business Transfers", body: [], list: [] },
      { id: "data-protection-measures", heading: "28. Data Protection", body: [], list: [] },
      { id: "no-absolute-security", heading: "29. No System Is Absolutely Secure", body: [] },
      { id: "data-retention", heading: "30. Data Retention", body: [], list: [] },
      { id: "data-deletion", heading: "31. Data Deletion", body: [], list: [] },
      { id: "childrens-data", heading: "32. Children's Data", body: [] },
      { id: "sensitive-data", heading: "33. Sensitive Data", body: [], list: [] },
      { id: "ai-and-data", heading: "34. Artificial Intelligence and Data", body: [], list: [] },
      { id: "ai-data-input", heading: "35. AI Data Input", body: [] },
      { id: "automated-decisions", heading: "36. Automated Decisions", body: [] },
      { id: "data-subject-rights", heading: "37. Data Subject Rights", body: [], list: [] },
      { id: "data-subject-requests", heading: "38. Data Subject Requests", body: [] },
      { id: "identity-verification", heading: "39. Identity Verification", body: [], list: [] },
      { id: "customer-representatives", heading: "40. Customer Representatives", body: [] },
      { id: "regulatory-requests", heading: "41. Regulatory Requests", body: [], list: [] },
      { id: "international-transfers", heading: "42. International Transfers", body: [] },
      { id: "vendor-security-privacy", heading: "43. Security and Privacy in Vendor Relationships", body: [], list: [] },
      { id: "payment-data", heading: "44. Payment Data", body: [] },
      { id: "support-communications", heading: "45. Communication and Support Data", body: [], list: [] },
      { id: "call-recording", heading: "46. Call Recording", body: [] },
      { id: "analytics", heading: "47. Analytics", body: [], list: [] },
      { id: "external-links", heading: "48. External Links", body: [], list: [] },
      { id: "shared-security-responsibility", heading: "49. Security as a Shared Responsibility", body: [], list: [] },
      { id: "data-breaches-incidents", heading: "50. Data Breaches and Security Incidents", body: [], list: [] },
      { id: "not-every-incident-a-breach", heading: "51. Not Every Technical Incident Is a Data Breach", body: [], list: [] },
      { id: "compliance-records", heading: "52. Retention of Compliance Records", body: [], list: [] },
      { id: "policy-changes", heading: "53. Changes to This Privacy Policy", body: [], list: [] },
      { id: "material-change-notices", heading: "54. Notice of Material Changes", body: [] },
      { id: "no-additional-contractual-rights", heading: "55. No Additional Contractual Rights Created", body: [], list: [] },
      { id: "ip-and-confidential-info", heading: "56. Protection of Intellectual Property and Confidential Information", body: [], list: [] },
      { id: "regulatory-compliance", heading: "57. Regulatory Compliance", body: [], list: [] },
      { id: "gdpr", heading: "58. GDPR", body: [], list: [] },
      { id: "ccpa-cpra", heading: "59. CCPA / CPRA", body: [], list: [] },
      { id: "no-sale-of-personal-data", heading: "60. No Sale of Personal Data", body: [] },
      { id: "do-not-sell-or-share", heading: "61. Do Not Sell or Share", body: [] },
      { id: "california-residents-rights", heading: "62. Rights of California Residents", body: [] },
      { id: "eu-eea-rights", heading: "63. Rights of EU and EEA Residents", body: [] },
      { id: "right-to-complain", heading: "64. Right to Lodge a Complaint", body: [] },
      { id: "not-legal-advice", heading: "65. No Legal Advice Provided", body: [], list: [] },
      { id: "dpa-relationship", heading: "66. Relationship with the Data Processing Agreement", body: [] },
      { id: "security-trust-policy-relationship", heading: "67. Relationship with the Security & Trust Policy", body: [] },
      { id: "security-compliance-docs-policy-relationship", heading: "68. Relationship with the Security & Compliance Documentation Request Policy", body: [] },
      { id: "privacy-requests", heading: "69. Privacy Requests", body: [], list: [] },
      { id: "legal-contact", heading: "70. Legal Communications", body: [] },
      { id: "security-contact", heading: "71. Security", body: [] },
      { id: "general-contact", heading: "72. General Contact", body: [], list: [] },
      { id: "effective-date", heading: "73. Effective Date", body: [] },
      { id: "document-history", heading: "74. Document History", body: [], list: [] },
      { id: "legal-disclaimer", heading: "75. Legal Disclaimer", body: [], list: [] },
      { id: "form-consent-notice", heading: "76. Short Consent Notice for Website Forms", body: [] },
    ],
  },
  {
    slug: "terms",
    navLabel: "Terms & Conditions",
    title: "Terms of Service",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction", heading: "1. Introduction", body: [] },
      { id: "definitions", heading: "2. Definitions", body: [] },
      { id: "acceptance-of-terms", heading: "3. Acceptance of Terms", body: [], list: [] },
      { id: "eligibility", heading: "4. Eligibility to Use", body: [] },
      { id: "account-registration", heading: "5. Account Registration", body: [], list: [] },
      { id: "account-responsibility", heading: "6. Account Responsibility", body: [], list: [] },
      { id: "authorized-users", heading: "7. Authorized Users", body: [] },
      { id: "provision-of-services", heading: "8. Provision of Services", body: [], list: [] },
      { id: "changes-to-services", heading: "9. Changes to the Services", body: [], list: [] },
      { id: "free-trials", heading: "10. Free Trials", body: [], list: [] },
      { id: "free-accounts", heading: "11. Free Accounts", body: [], list: [] },
      { id: "paid-subscriptions", heading: "12. Paid Subscriptions", body: [], list: [] },
      { id: "pricing", heading: "13. Pricing", body: [], list: [] },
      { id: "billing", heading: "14. Billing", body: [], list: [] },
      { id: "taxes", heading: "15. Taxes", body: [] },
      { id: "late-payment", heading: "16. Late Payment", body: [], list: [] },
      { id: "renewal-cancellation", heading: "17. Renewal", body: [] },
      { id: "cancellation", heading: "18. Cancellation", body: [], list: [] },
      { id: "refunds", heading: "19. Refunds", body: [] },
      { id: "service-suspension", heading: "20. Suspension of Service", body: [], list: [] },
      { id: "urgent-security-suspension", heading: "21. Urgent Security Suspension", body: [], list: [] },
      { id: "zynreach-ownership", heading: "22. ZynReach Ownership", body: [], list: [] },
      { id: "license-to-use-services", heading: "23. License to Use the Services", body: [], list: [] },
      { id: "usage-restrictions", heading: "24. Usage Restrictions", body: [], list: [] },
      { id: "customer-data", heading: "25. Customer Data", body: [], list: [] },
      { id: "customer-data-responsibility", heading: "26. Customer Responsibility for Data", body: [], list: [] },
      { id: "data-protection-privacy", heading: "27. Data Protection and Privacy", body: [] },
      { id: "data-processing-agreement", heading: "28. Data Processing Agreement", body: [] },
      { id: "security", heading: "29. Security", body: [] },
      { id: "security-incidents", heading: "30. Security Incidents", body: [] },
      { id: "sub-processors", heading: "31. Sub-processors", body: [] },
      { id: "external-services", heading: "32. External Services", body: [], list: [] },
      { id: "third-party-services", heading: "33. Third-Party Services", body: [], list: [] },
      { id: "artificial-intelligence", heading: "34. Artificial Intelligence", body: [], list: [] },
      { id: "ip-inputs-outputs", heading: "35. Intellectual Property in Inputs and Outputs", body: [], list: [] },
      { id: "feedback", heading: "36. Feedback", body: [] },
      { id: "confidentiality", heading: "37. Confidentiality", body: [] },
      { id: "confidentiality-exceptions", heading: "38. Exceptions to Confidentiality", body: [], list: [] },
      { id: "compliance-with-laws", heading: "39. Compliance with Laws", body: [] },
      { id: "regulated-industries", heading: "40. Regulated Industries", body: [], list: [] },
      { id: "acceptable-use-policy", heading: "41. Acceptable Use Policy", body: [] },
      { id: "customer-responsibilities", heading: "42. Customer Responsibilities", body: [], list: [] },
      { id: "technical-support", heading: "43. Technical Support", body: [], list: [] },
      { id: "service-levels", heading: "44. Service Levels", body: [] },
      { id: "maintenance", heading: "45. Maintenance", body: [], list: [] },
      { id: "beta-features", heading: "46. Beta Features", body: [], list: [] },
      { id: "content-and-data", heading: "47. Content and Data", body: [], list: [] },
      { id: "backups", heading: "48. Backups", body: [] },
      { id: "data-retention-deletion", heading: "49. Data Retention & Deletion", body: [] },
      { id: "termination-by-customer", heading: "50. Termination by the Customer", body: [] },
      { id: "termination-by-zynreach", heading: "51. Termination by ZynReach", body: [], list: [] },
      { id: "effect-of-termination", heading: "52. Effect of Termination", body: [], list: [] },
      { id: "surviving-provisions", heading: "53. Provisions Surviving Termination", body: [], list: [] },
      { id: "disclaimer-of-warranties", heading: "54. Disclaimer of Warranties", body: [], list: [] },
      { id: "reliance-on-service", heading: "55. Reliance on the Service", body: [] },
      { id: "limitation-of-liability", heading: "56. Limitation of Liability", body: [], list: [] },
      { id: "liability-cap", heading: "57. Maximum Liability Cap", body: [] },
      { id: "liability-exceptions", heading: "58. Exceptions to Liability Limitations", body: [] },
      { id: "indemnification-of-zynreach", heading: "59. Indemnification of ZynReach", body: [], list: [] },
      { id: "indemnification-procedures", heading: "60. Indemnification Procedures", body: [], list: [] },
      { id: "force-majeure", heading: "61. Force Majeure", body: [], list: [] },
      { id: "notices", heading: "62. Notices", body: [], list: [] },
      { id: "amendments-to-terms", heading: "63. Amendments to the Terms", body: [], list: [] },
      { id: "notice-of-material-changes", heading: "64. Notice of Material Changes", body: [], list: [] },
      { id: "continued-use", heading: "65. Continued Use", body: [] },
      { id: "no-waiver", heading: "66. No Waiver", body: [] },
      { id: "severability", heading: "67. Severability", body: [] },
      { id: "no-agency", heading: "68. No Agency", body: [], list: [] },
      { id: "assignment", heading: "69. Assignment of the Agreement", body: [] },
      { id: "entire-agreement", heading: "70. Entire Agreement", body: [], list: [] },
      { id: "order-of-precedence", heading: "71. Order of Precedence", body: [], list: [] },
      { id: "governing-law", heading: "72. Governing Law", body: [] },
      { id: "jurisdiction-dispute-resolution", heading: "73. Jurisdiction and Dispute Resolution", body: [] },
      { id: "consumer-users", heading: "74. Consumer Users", body: [] },
      { id: "government-enterprise-services", heading: "75. Government and Enterprise Services", body: [] },
      { id: "export-controls", heading: "76. Export Controls", body: [] },
      { id: "anti-bribery-corruption", heading: "77. Anti-Bribery and Anti-Corruption", body: [], list: [] },
      { id: "anti-fraud", heading: "78. Anti-Fraud", body: [], list: [] },
      { id: "platform-misuse", heading: "79. Misuse of the Platform", body: [], list: [] },
      { id: "no-general-monitoring-obligation", heading: "80. No Obligation of General Monitoring", body: [] },
      { id: "customer-security", heading: "81. Customer Security", body: [], list: [] },
      { id: "integrations-api", heading: "82. Integrations and API", body: [], list: [] },
      { id: "api-changes", heading: "83. API Changes", body: [] },
      { id: "data-availability-after-termination", heading: "84. Data Availability After Termination", body: [], list: [] },
      { id: "responsibility-for-copies", heading: "85. Responsibility for Copies", body: [] },
      { id: "marketing-communications", heading: "86. Marketing Communications", body: [], list: [] },
      { id: "trademarks", heading: "87. Trademarks", body: [] },
      { id: "external-links", heading: "88. External Links", body: [] },
      { id: "advertisements-partners", heading: "89. Advertisements and Partners", body: [] },
      { id: "trial-provisions", heading: "90. Special Provisions for Trial Versions", body: [] },
      { id: "enterprise-plan-provisions", heading: "91. Special Provisions for Enterprise Plans", body: [], list: [] },
      { id: "data-residency", heading: "92. Data Residency", body: [] },
      { id: "security-support-for-customers", heading: "93. Security Support for Customers", body: [] },
      { id: "post-incident-obligations", heading: "94. Post-Incident Obligations", body: [], list: [] },
      { id: "no-professional-advice", heading: "95. No Professional Advice", body: [], list: [] },
      { id: "accuracy-of-information", heading: "96. Accuracy of Information", body: [] },
      { id: "security-and-compliance", heading: "97. Security and Compliance", body: [], list: [] },
      { id: "legal-communications", heading: "98. Legal Communications", body: [] },
      { id: "operational-communications", heading: "99. Operational Communications", body: [] },
      { id: "document-record", heading: "100. Document Record", body: [], list: [] },
      { id: "final-acknowledgment", heading: "101. Final Acknowledgment", body: [], list: [] },
      { id: "legal-notice", heading: "102. Legal Notice", body: [] },
    ],
  },
  {
    slug: "data-retention",
    navLabel: "Data Retention & Deletion",
    title: "Data Retention & Deletion Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of the Policy", body: [], list: [] },
      { id: "scope", heading: "2. Scope of Application", body: [], list: [] },
      { id: "core-principles", heading: "3. Core Principles of Data Retention", body: [], list: [] },
      { id: "categories-of-data", heading: "4. Categories of Data", body: [], list: [] },
      { id: "retention-schedule", heading: "5. Data Retention Schedule", body: [], list: [] },
      { id: "customer-data-responsibility", heading: "6. Customer Data & Retention Responsibility", body: [], list: [] },
      { id: "end-of-subscription", heading: "7. End of Customer Subscription & Data Deletion", body: [], list: [] },
      { id: "backups", heading: "8. Backups", body: [], list: [] },
      { id: "secure-deletion", heading: "9. Secure Deletion & Anonymization", body: [], list: [] },
      { id: "legal-hold", heading: "10. Legally Required Data & Legal Hold", body: [], list: [] },
      { id: "individual-requests", heading: "11. Individual Deletion Requests", body: [], list: [] },
      { id: "account-inactive", heading: "12. Account Data & Inactive Accounts", body: [], list: [] },
      { id: "marketing-correspondence", heading: "13. Marketing Data & Correspondence", body: [], list: [] },
      { id: "system-security-logs", heading: "14. System, Security & Audit Logs", body: [], list: [] },
      { id: "sub-processors", heading: "15. Sub-processors & Independent Third Parties", body: [], list: [] },
      { id: "lifecycle-classification", heading: "16. Data Lifecycle & Classification", body: [], list: [] },
      { id: "minimum-retention", heading: "17. Minimum Retention & Periodic Review", body: [], list: [] },
      { id: "internal-access", heading: "18. Internal Access & Termination of Access", body: [], list: [] },
      { id: "temporary-cached", heading: "19. Temporary & Cached Data, and Technical Logs", body: [], list: [] },
      { id: "multi-phase-deletion", heading: "20. Multi-Phase Deletion at Service Termination & Exceptions", body: [], list: [] },
      { id: "technical-limitations", heading: "21. Technical Limitations & No Guarantee of Immediate Deletion", body: [] },
      { id: "proof-of-deletion", heading: "22. Proof of Deletion & Customer Requests", body: [], list: [] },
      { id: "relationship-to-other-policies", heading: "23. Relationship to Other Policies", body: [], list: [] },
      { id: "compliance-changes", heading: "24. Compliance & Changes to This Policy", body: [], list: [] },
      { id: "precedence-contact", heading: "25. Order of Precedence & Contact", body: [], list: [] },
      { id: "legal-notice", heading: "26. Legal Notice", body: [], list: [] },
    ],
  },
  {
    slug: "acceptable-use",
    navLabel: "Acceptable Use",
    title: "Acceptable Use Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of the Policy", body: [], list: [] },
      { id: "scope-definitions", heading: "2. Scope of Application & Definition of Services", body: [], list: [] },
      { id: "permitted-use", heading: "3. Permitted Use & Compliance with Laws", body: [], list: [] },
      { id: "hacking-access", heading: "4. Hacking, Cyberattacks & Unauthorized Account Access", body: [], list: [] },
      { id: "malware", heading: "5. Malware", body: [], list: [] },
      { id: "phishing-fraud", heading: "6. Phishing, Fraud & Impersonation", body: [], list: [] },
      { id: "spam", heading: "7. Spam & Unsolicited Messages", body: [], list: [] },
      { id: "resource-abuse", heading: "8. Resource Abuse, Rate Limits & Denial-of-Service", body: [], list: [] },
      { id: "security-scanning", heading: "9. Security Scanning & Penetration Testing", body: [], list: [] },
      { id: "unlawful-data-collection", heading: "10. Unlawful Data Collection & Sensitive Data", body: [], list: [] },
      { id: "unlawful-content-ip", heading: "11. Unlawful Content & Intellectual Property", body: [], list: [] },
      { id: "privacy-financial", heading: "12. Privacy Violations & Financial Information", body: [], list: [] },
      { id: "harmful-content", heading: "13. Harmful Content & High-Risk Uses", body: [], list: [] },
      { id: "ai", heading: "14. Artificial Intelligence", body: [], list: [] },
      { id: "automation-scraping", heading: "15. Automation, Web Scraping & Trial Accounts", body: [], list: [] },
      { id: "login-credentials", heading: "16. Login Credentials & Customer Responsibility for Users", body: [], list: [] },
      { id: "user-content", heading: "17. User-Submitted Content & No Implied Consent", body: [], list: [] },
      { id: "monitoring-investigation", heading: "18. Security Monitoring & Investigation of Violations", body: [], list: [] },
      { id: "suspension-emergency", heading: "19. Suspension of Accounts & Emergency Action", body: [], list: [] },
      { id: "content-removal", heading: "20. Content Removal & Government Requests", body: [], list: [] },
      { id: "reporting-abuse", heading: "21. Reporting Abuse & False Reports", body: [], list: [] },
      { id: "vulnerability-reporting", heading: "22. Vulnerability Reporting", body: [] },
      { id: "relationship-to-other-policies", heading: "23. Relationship to Other Policies", body: [] },
      { id: "enforcement-actions", heading: "24. Enforcement Actions & Factors Considered", body: [], list: [] },
      { id: "service-restoration", heading: "25. Service Restoration & Third-Party Responsibility", body: [], list: [] },
      { id: "commercial-restrictions", heading: "26. Commercial Restrictions, Resale & Trademark Use", body: [], list: [] },
      { id: "liability-limits", heading: "27. Limits of ZynReach's Liability", body: [], list: [] },
      { id: "amendments", heading: "28. Amendments to This Policy & Their Effect", body: [], list: [] },
      { id: "precedence-severability", heading: "29. Order of Precedence, Severability & No Waiver", body: [], list: [] },
      { id: "contact", heading: "30. Contact & Legal Notice", body: [], list: [] },
    ],
  },
  {
    slug: "security-trust-policy",
    navLabel: "Security & Trust",
    title: "Security & Trust Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "introduction", heading: "1. Introduction", body: [], list: [] },
      { id: "purpose", heading: "2. Purpose", body: [], list: [] },
      { id: "scope", heading: "3. Scope of the Policy", body: [], list: [] },
      { id: "principles", heading: "4. Security and Trust Principles", body: [] },
      { id: "information-classification", heading: "5. Information Classification", body: [], list: [] },
      { id: "customer-data-protection", heading: "6. Protection of Customer Data", body: [], list: [] },
      { id: "encryption", heading: "7. Encryption", body: [] },
      { id: "identity-access-management", heading: "8. Identity and Access Management", body: [], list: [] },
      { id: "multi-factor-authentication", heading: "9. Multi-Factor Authentication", body: [], list: [] },
      { id: "privilege-management", heading: "10. Privilege Management", body: [], list: [] },
      { id: "privileged-access", heading: "11. Administrative and Privileged Access", body: [], list: [] },
      { id: "audit-logging", heading: "12. Audit Logging", body: [], list: [] },
      { id: "audit-log-integrity", heading: "13. Integrity of Audit Logs", body: [], list: [] },
      { id: "secure-software-development", heading: "14. Secure Software Development", body: [], list: [] },
      { id: "vulnerability-management", heading: "15. Vulnerability Management", body: [], list: [] },
      { id: "security-testing", heading: "16. Security Testing", body: [], list: [] },
      { id: "security-monitoring", heading: "17. Security Monitoring", body: [] },
      { id: "incident-management", heading: "18. Security Incident Management", body: [], list: [] },
      { id: "customer-incident-notification", heading: "19. Customer Incident Notification", body: [], list: [] },
      { id: "backups", heading: "20. Backup", body: [], list: [] },
      { id: "disaster-recovery", heading: "21. Disaster Recovery", body: [], list: [] },
      { id: "business-continuity", heading: "22. Business Continuity", body: [], list: [] },
      { id: "infrastructure-security", heading: "23. Infrastructure Security", body: [], list: [] },
      { id: "subprocessors", heading: "24. Vendors and Sub-Processors", body: [], list: [] },
      { id: "vendor-risk-management", heading: "25. Vendor Risk Management", body: [], list: [] },
      { id: "data-protection-privacy", heading: "26. Data Protection and Privacy", body: [] },
      { id: "data-minimization", heading: "27. Data Minimization Principle", body: [] },
      { id: "data-retention-deletion", heading: "28. Data Retention and Deletion", body: [], list: [] },
      { id: "international-data-transfers", heading: "29. International Data Transfers", body: [] },
      { id: "personnel-security", heading: "30. Personnel and Contractor Security", body: [], list: [] },
      { id: "access-termination", heading: "31. Access Termination", body: [] },
      { id: "api-integration-security", heading: "32. Integration and API Security", body: [] },
      { id: "ai-security", heading: "33. Artificial Intelligence Security", body: [], list: [] },
      { id: "shared-responsibility", heading: "34. Shared Responsibility", body: [], list: [] },
      { id: "customer-security", heading: "35. Customer Security", body: [], list: [] },
      { id: "vulnerability-disclosure", heading: "36. Vulnerability Disclosure", body: [], list: [] },
      { id: "offensive-security-testing", heading: "37. Offensive Security Testing", body: [], list: [] },
      { id: "compliance-frameworks", heading: "38. Compliance and Security Frameworks", body: [], list: [] },
      { id: "no-absolute-compliance-guarantee", heading: "39. No Absolute Compliance Guarantee", body: [], list: [] },
      { id: "accuracy-of-claims", heading: "40. Accuracy of Security and Compliance Claims", body: [], list: [] },
      { id: "security-documentation", heading: "41. Security Documentation", body: [], list: [] },
      { id: "confidentiality-of-security-info", heading: "42. Confidentiality and Protection of Security Information", body: [], list: [] },
      { id: "no-absolute-security-guarantee", heading: "43. No Absolute Security Guarantee", body: [], list: [] },
      { id: "limitation-of-liability", heading: "44. Limitation of Liability", body: [], list: [] },
      { id: "change-management", heading: "45. Change Management", body: [], list: [] },
      { id: "related-legal-documents", heading: "46. Relationship with Other Legal Documents", body: [], list: [] },
      { id: "intellectual-property", heading: "47. Intellectual Property Rights", body: [] },
      { id: "contact", heading: "48. Contact", body: [], list: [] },
      { id: "security-notification", heading: "49. Security Notification", body: [], list: [] },
      { id: "trust-statement", heading: "50. Statement of Trust", body: [] },
      { id: "legal-disclaimer", heading: "51. Legal Disclaimer", body: [], list: [] },
      { id: "document-version-record", heading: "52. Document Version History", body: [], list: [] },
    ],
  },
  {
    slug: "incident-response",
    navLabel: "Incident Response",
    title: "Incident Response & Security Breach Notification Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of the Policy", body: [], list: [] },
      { id: "scope", heading: "2. Scope of the Policy", body: [], list: [] },
      { id: "definitions", heading: "3. Definitions", body: [] },
      { id: "core-principles", heading: "4. Core Principles of Incident Response", body: [] },
      { id: "lifecycle", heading: "5. Incident Response Lifecycle", body: [] },
      { id: "detection", heading: "6. Incident Detection", body: [], list: [] },
      { id: "reporting", heading: "7. Reporting a Security Incident", body: [], list: [] },
      { id: "initial-assessment", heading: "8. Initial Incident Assessment", body: [], list: [] },
      { id: "classification", heading: "9. Incident Classification", body: [], list: [] },
      { id: "response-team", heading: "10. Incident Response Team", body: [], list: [] },
      { id: "authority-during-incident", heading: "11. Authority During an Incident", body: [], list: [] },
      { id: "containment", heading: "12. Containment", body: [], list: [] },
      { id: "technical-investigation", heading: "13. Technical Investigation", body: [], list: [] },
      { id: "evidence-preservation", heading: "14. Evidence Preservation", body: [], list: [] },
      { id: "eradication", heading: "15. Eradication of the Incident's Cause", body: [], list: [] },
      { id: "service-recovery", heading: "16. Service Recovery", body: [], list: [] },
      { id: "data-breach-assessment", heading: "17. Assessing Whether an Incident Constitutes a Data Breach", body: [], list: [] },
      { id: "customer-notification", heading: "18. Notification to Customers", body: [], list: [] },
      { id: "phased-notification", heading: "19. Phased Notification", body: [] },
      { id: "notification-content", heading: "20. Notification Content", body: [], list: [] },
      { id: "notification-timing", heading: "21. Notification Timing", body: [], list: [] },
      { id: "notification-on-behalf-of-customer", heading: "22. Notification on Behalf of the Customer", body: [], list: [] },
      { id: "regulatory-notification", heading: "23. Notification to Regulatory Authorities", body: [], list: [] },
      { id: "data-subject-notification", heading: "24. Notification to Data Subjects", body: [], list: [] },
      { id: "public-communications", heading: "25. Public Communications", body: [], list: [] },
      { id: "investigation-confidentiality", heading: "26. Confidentiality of the Investigation", body: [], list: [] },
      { id: "sub-processor-incidents", heading: "27. Incidents at Sub-processors", body: [], list: [] },
      { id: "account-incidents", heading: "28. Account-Related Incidents", body: [], list: [] },
      { id: "customer-responsibility", heading: "29. Customer Responsibility", body: [], list: [] },
      { id: "customer-cooperation", heading: "30. Cooperation with the Customer", body: [], list: [] },
      { id: "response-costs", heading: "31. Cost of Response", body: [] },
      { id: "external-experts", heading: "32. Engagement of External Experts", body: [], list: [] },
      { id: "law-enforcement", heading: "33. Dealing with Law Enforcement Authorities", body: [], list: [] },
      { id: "harm-assessment", heading: "34. Harm Assessment", body: [], list: [] },
      { id: "corrective-actions", heading: "35. Corrective Actions", body: [], list: [] },
      { id: "post-incident-review", heading: "36. Post-Incident Review", body: [], list: [] },
      { id: "records-documentation", heading: "37. Records and Documentation", body: [], list: [] },
      { id: "response-plan-testing", heading: "38. Testing the Response Plan", body: [], list: [] },
      { id: "business-continuity-relationship", heading: "39. Relationship with Business Continuity & Disaster Recovery", body: [], list: [] },
      { id: "limits-of-commitment", heading: "40. Limits of Commitment", body: [], list: [] },
      { id: "no-admission-of-liability", heading: "41. No Admission of Liability", body: [], list: [] },
      { id: "protection-of-sensitive-information", heading: "42. Protection of Sensitive Information", body: [], list: [] },
      { id: "handling-vulnerabilities", heading: "43. Handling Vulnerabilities", body: [], list: [] },
      { id: "responsible-disclosure", heading: "44. Responsible Disclosure", body: [] },
      { id: "employee-obligations", heading: "45. Obligations of ZynReach Personnel", body: [], list: [] },
      { id: "policy-review", heading: "46. Policy Review", body: [], list: [] },
      { id: "amendments", heading: "47. Amendments", body: [], list: [] },
      { id: "legal-precedence", heading: "48. Legal Precedence", body: [], list: [] },
      { id: "incident-communications", heading: "49. Communications Regarding Incidents", body: [], list: [] },
      { id: "document-record", heading: "50. Document Record", body: [], list: [] },
      { id: "legal-notice", heading: "51. Legal Notice", body: [], list: [] },
    ],
  },
  {
    slug: "vulnerability-disclosure",
    navLabel: "Vulnerability Disclosure",
    title: "Vulnerability Disclosure Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [], list: [] },
      { id: "scope", heading: "2. Scope of the Policy", body: [], list: [] },
      { id: "out-of-scope-assets", heading: "3. Out-of-Scope Assets", body: [], list: [] },
      { id: "purpose-of-testing", heading: "4. Purpose of Testing", body: [] },
      { id: "vulnerability-definition", heading: "5. Definition of a Security Vulnerability", body: [], list: [] },
      { id: "responsible-disclosure", heading: "6. Responsible Disclosure", body: [] },
      { id: "security-reporting", heading: "7. Security Reporting", body: [] },
      { id: "report-information", heading: "8. Report Information", body: [], list: [] },
      { id: "minimum-proof", heading: "9. Minimum Proof Required", body: [] },
      { id: "data-accessed-during-testing", heading: "10. Data Accessed During Testing", body: [], list: [] },
      { id: "no-customer-data-access", heading: "11. No Access to Customer Data", body: [] },
      { id: "no-data-modification", heading: "12. No Data Modification", body: [], list: [] },
      { id: "no-service-disruption", heading: "13. No Service Disruption", body: [], list: [] },
      { id: "no-stress-testing", heading: "14. No Stress Testing", body: [], list: [] },
      { id: "no-malicious-software", heading: "15. No Use of Malicious Software", body: [], list: [] },
      { id: "no-exploitation-after-proof", heading: "16. No Exploitation After Proof of Concept", body: [], list: [] },
      { id: "no-third-party-access", heading: "17. No Use of the Vulnerability to Access Third Parties", body: [], list: [] },
      { id: "account-takeover", heading: "18. Account Takeover", body: [], list: [] },
      { id: "authentication-testing", heading: "19. Authentication Testing", body: [], list: [] },
      { id: "authorization-testing", heading: "20. Authorization Testing", body: [] },
      { id: "automated-scanning", heading: "21. Automated Scanning", body: [], list: [] },
      { id: "rate-limiting", heading: "22. Rate Limiting", body: [] },
      { id: "social-engineering", heading: "23. Social Engineering", body: [], list: [] },
      { id: "physical-security-testing", heading: "24. Physical Security Testing", body: [] },
      { id: "employee-testing", heading: "25. Employee Testing", body: [], list: [] },
      { id: "third-party-services", heading: "26. Third-Party Services", body: [] },
      { id: "shared-vulnerabilities", heading: "27. Shared Vulnerabilities", body: [] },
      { id: "safe-harbor", heading: "28. Safe Harbor", body: [], list: [] },
      { id: "good-faith", heading: "29. Good Faith", body: [], list: [] },
      { id: "do-no-harm", heading: "30. Do No Harm", body: [], list: [] },
      { id: "stopping-testing", heading: "31. Stopping Testing", body: [], list: [] },
      { id: "cleanup", heading: "32. Cleanup", body: [], list: [] },
      { id: "no-data-retention", heading: "33. No Data Retention", body: [] },
      { id: "proof-of-concept", heading: "34. Proof of Concept", body: [], list: [] },
      { id: "severity-classification", heading: "35. Severity Classification", body: [], list: [] },
      { id: "final-severity-determination", heading: "36. Final Severity Determination", body: [], list: [] },
      { id: "report-verification", heading: "37. Report Verification", body: [], list: [] },
      { id: "communication-with-researcher", heading: "38. Communication with the Researcher", body: [], list: [] },
      { id: "response-time", heading: "39. Response Time", body: [], list: [] },
      { id: "vulnerability-verification", heading: "40. Vulnerability Verification", body: [], list: [] },
      { id: "false-positive", heading: "41. False Positive", body: [], list: [] },
      { id: "duplicate-reports", heading: "42. Duplicate Reports", body: [] },
      { id: "informational-reports", heading: "43. Informational Reports", body: [] },
      { id: "security-best-practices", heading: "44. Security Best Practices", body: [] },
      { id: "ineligible-reports", heading: "45. Ineligible Reports", body: [], list: [] },
      { id: "social-engineering-reports", heading: "46. Social Engineering Reports", body: [] },
      { id: "physical-testing-reports", heading: "47. Physical Testing Reports", body: [] },
      { id: "denial-of-service", heading: "48. Denial of Service", body: [] },
      { id: "spam", heading: "49. Spam", body: [], list: [] },
      { id: "privacy", heading: "50. Privacy", body: [] },
      { id: "confidentiality", heading: "51. Confidentiality", body: [], list: [] },
      { id: "public-disclosure", heading: "52. Public Disclosure", body: [] },
      { id: "coordinated-disclosure", heading: "53. Coordinated Disclosure", body: [], list: [] },
      { id: "disclosure-timeline", heading: "54. Disclosure Timeline", body: [], list: [] },
      { id: "mandatory-disclosure", heading: "55. Mandatory Disclosure", body: [] },
      { id: "customer-data", heading: "56. Customer Data", body: [], list: [] },
      { id: "researcher-attribution", heading: "57. Security Researcher Attribution", body: [] },
      { id: "no-compensation", heading: "58. No Compensation", body: [], list: [] },
      { id: "bug-bounty", heading: "59. Bug Bounty", body: [], list: [] },
      { id: "no-employment-relationship", heading: "60. No Employment Relationship", body: [], list: [] },
      { id: "no-ownership-rights", heading: "61. No Grant of Ownership Rights", body: [], list: [] },
      { id: "no-trademark-use", heading: "62. No Use of the Trademark", body: [] },
      { id: "policy-misuse", heading: "63. Misuse of the Policy", body: [], list: [] },
      { id: "extortion", heading: "64. Extortion", body: [] },
      { id: "threatening-disclosure", heading: "65. Threatening Disclosure", body: [] },
      { id: "handling-malicious-reports", heading: "66. Handling Malicious Reports", body: [], list: [] },
      { id: "legal-cooperation", heading: "67. Legal Cooperation", body: [] },
      { id: "good-faith-researcher-protection", heading: "68. Protection of the Good-Faith Researcher", body: [] },
      { id: "safe-harbor-limitations", heading: "69. Safe Harbor Limitations", body: [], list: [] },
      { id: "scope-changes", heading: "70. Scope Changes", body: [] },
      { id: "emergency-security-actions", heading: "71. Emergency Security Actions", body: [], list: [] },
      { id: "request-stop-testing", heading: "72. Request to Stop Testing", body: [], list: [] },
      { id: "service-changes", heading: "73. Service Changes", body: [], list: [] },
      { id: "researcher-responsibility", heading: "74. Researcher Responsibility", body: [], list: [] },
      { id: "zynreach-responsibility", heading: "75. ZynReach's Responsibility", body: [], list: [] },
      { id: "no-immediate-remediation-guarantee", heading: "76. No Guarantee of Immediate Remediation", body: [] },
      { id: "security-fix", heading: "77. Security Fix", body: [], list: [] },
      { id: "compensating-controls", heading: "78. Compensating Controls", body: [] },
      { id: "regression-testing", heading: "79. Regression Testing", body: [], list: [] },
      { id: "security-advisory", heading: "80. Security Advisory", body: [], list: [] },
      { id: "cve", heading: "81. CVE", body: [] },
      { id: "policy-updates", heading: "82. Policy Updates", body: [], list: [] },
      { id: "effective-version", heading: "83. Effective Version", body: [] },
      { id: "governing-law", heading: "84. Governing Law", body: [] },
      { id: "no-waiver", heading: "85. No Waiver", body: [] },
      { id: "severability", heading: "86. Severability", body: [] },
      { id: "relationship-with-other-policies", heading: "87. Relationship with Other Policies", body: [], list: [] },
      { id: "no-modification-of-agreements", heading: "88. No Modification of Agreements", body: [], list: [] },
      { id: "security-contact", heading: "89. Security Contact", body: [] },
      { id: "emergency-contact", heading: "90. Emergency Contact", body: [], list: [] },
      { id: "minimum-report-content", heading: "91. Minimum Report Content", body: [], list: [] },
      { id: "researcher-privacy", heading: "92. Researcher Privacy", body: [] },
      { id: "confidentiality-of-reports", heading: "93. Confidentiality of Reports", body: [] },
      { id: "no-public-exploit-development", heading: "94. No Public Exploit Development", body: [] },
      { id: "production-safety", heading: "95. Production Safety", body: [] },
      { id: "test-accounts", heading: "96. Test Accounts", body: [], list: [] },
      { id: "minimal-impact-principle", heading: "97. Minimal Impact Principle", body: [] },
      { id: "security-first", heading: "98. Security First", body: [] },
      { id: "final-authority", heading: "99. Final Authority", body: [], list: [] },
      { id: "document-record", heading: "100. Document Record", body: [], list: [] },
      { id: "document-approval", heading: "101. Document Approval", body: [], list: [] },
      { id: "legal-notice", heading: "102. Legal Notice", body: [] },
    ],
  },
  {
    slug: "business-continuity",
    navLabel: "Business Continuity & Disaster Recovery",
    title: "Business Continuity & Disaster Recovery Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [], list: [] },
      { id: "scope", heading: "2. Scope of the Policy", body: [], list: [] },
      { id: "continuity-objectives", heading: "3. Continuity Objectives", body: [], list: [] },
      { id: "bcdr-principles", heading: "4. BCDR Principles", body: [], list: [] },
      { id: "disaster-definition", heading: "5. Definition of a Disaster", body: [], list: [] },
      { id: "business-continuity", heading: "6. Business Continuity", body: [] },
      { id: "disaster-recovery", heading: "7. Disaster Recovery", body: [], list: [] },
      { id: "business-impact-analysis", heading: "8. Business Impact Analysis", body: [], list: [] },
      { id: "system-classification", heading: "9. System Classification", body: [], list: [] },
      { id: "recovery-prioritization", heading: "10. Recovery Prioritization", body: [], list: [] },
      { id: "rto", heading: "11. Recovery Time Objective — RTO", body: [] },
      { id: "rpo", heading: "12. Recovery Point Objective — RPO", body: [], list: [] },
      { id: "rto-rpo-matrix", heading: "13. RTO/RPO Matrix", body: [], list: [] },
      { id: "bc-plans", heading: "14. Business Continuity Plans", body: [], list: [] },
      { id: "dr-plan", heading: "15. Disaster Recovery Plan", body: [], list: [] },
      { id: "dr-architecture", heading: "16. Disaster Recovery Architecture", body: [], list: [] },
      { id: "cloud-dependency", heading: "17. Cloud Dependency", body: [] },
      { id: "third-party-dependencies", heading: "18. Third-Party Dependencies", body: [], list: [] },
      { id: "vendor-continuity", heading: "19. Vendor Continuity", body: [], list: [] },
      { id: "backups", heading: "20. Backups", body: [], list: [] },
      { id: "backup-protection", heading: "21. Protection of Backups", body: [], list: [] },
      { id: "backup-retention", heading: "22. Backup Retention", body: [], list: [] },
      { id: "backup-testing", heading: "23. Backup Testing", body: [] },
      { id: "database-recovery", heading: "24. Database Recovery", body: [], list: [] },
      { id: "data-integrity", heading: "25. Data Integrity", body: [] },
      { id: "failover", heading: "26. Failover", body: [] },
      { id: "failback", heading: "27. Failback", body: [] },
      { id: "crisis-management", heading: "28. Crisis Management", body: [], list: [] },
      { id: "incident-commander", heading: "29. Incident Commander", body: [], list: [] },
      { id: "disaster-declaration", heading: "30. Disaster Declaration", body: [], list: [] },
      { id: "incident-severity-levels", heading: "31. Incident Severity Levels", body: [], list: [] },
      { id: "escalation", heading: "32. Escalation", body: [], list: [] },
      { id: "crisis-communication", heading: "33. Communication During Disasters", body: [], list: [] },
      { id: "customer-communication", heading: "34. Customer Communication", body: [], list: [] },
      { id: "status-page", heading: "35. Status Page", body: [], list: [] },
      { id: "crisis-communication-security", heading: "36. Security of Communications During a Crisis", body: [] },
      { id: "cyber-disaster-recovery", heading: "37. Cyber Disaster Recovery", body: [], list: [] },
      { id: "ransomware-response", heading: "38. Ransomware Response", body: [], list: [] },
      { id: "backup-protection-attacks", heading: "39. Protecting Backups from Attacks", body: [] },
      { id: "recovery-validation", heading: "40. Recovery Validation", body: [], list: [] },
      { id: "post-recovery-monitoring", heading: "41. Post-Recovery Monitoring", body: [] },
      { id: "alternative-communication-plan", heading: "42. Alternative Communication Plan", body: [] },
      { id: "remote-operations", heading: "43. Remote Operations", body: [] },
      { id: "essential-personnel", heading: "44. Essential Personnel", body: [], list: [] },
      { id: "role-redundancy", heading: "45. Role Redundancy", body: [], list: [] },
      { id: "asset-management", heading: "46. Asset Management", body: [] },
      { id: "recovery-procedures-documentation", heading: "47. Documentation of Recovery Procedures", body: [] },
      { id: "recovery-procedures-control", heading: "48. Control Over Recovery Procedures", body: [] },
      { id: "change-management-during-disasters", heading: "49. Change Management During Disasters", body: [] },
      { id: "emergency-changes", heading: "50. Emergency Changes", body: [], list: [] },
      { id: "decision-documentation", heading: "51. Documentation of Decisions", body: [], list: [] },
      { id: "testing-program", heading: "52. Testing Program", body: [], list: [] },
      { id: "tabletop-testing", heading: "53. Tabletop Testing", body: [] },
      { id: "recovery-testing", heading: "54. Recovery Testing", body: [] },
      { id: "test-results-documentation", heading: "55. Documentation of Test Results", body: [], list: [] },
      { id: "lessons-learned", heading: "56. Lessons Learned", body: [] },
      { id: "corrective-actions", heading: "57. Corrective Actions", body: [], list: [] },
      { id: "bcdr-review", heading: "58. Review of the BCDR Program", body: [], list: [] },
      { id: "change-management-impact", heading: "59. Change Management (Impact Review)", body: [], list: [] },
      { id: "vendor-risk-management", heading: "60. Vendor Risk Management", body: [] },
      { id: "external-service-dependency", heading: "61. Dependency on External Services", body: [] },
      { id: "data-security-during-recovery", heading: "62. Data Security During Recovery", body: [] },
      { id: "access-during-recovery", heading: "63. Access During Recovery", body: [], list: [] },
      { id: "secrets-protection", heading: "64. Protection of Secrets", body: [], list: [] },
      { id: "data-retention-during-disaster", heading: "65. Data Retention During a Disaster", body: [] },
      { id: "data-deletion-during-disaster", heading: "66. Data Deletion During a Disaster", body: [] },
      { id: "dr-documentation", heading: "67. Disaster Recovery Documentation", body: [], list: [] },
      { id: "recovery-runbooks", heading: "68. Recovery Runbooks", body: [] },
      { id: "runbook-access", heading: "69. Access to Runbooks", body: [] },
      { id: "bc-committee", heading: "70. Business Continuity Committee", body: [], list: [] },
      { id: "management-responsibilities", heading: "71. Management Responsibilities", body: [], list: [] },
      { id: "security-team-responsibilities", heading: "72. Security Team Responsibilities", body: [], list: [] },
      { id: "engineering-infrastructure-responsibilities", heading: "73. Engineering / Infrastructure Responsibilities", body: [], list: [] },
      { id: "customer-support-responsibilities", heading: "74. Customer Support Responsibilities", body: [], list: [] },
      { id: "legal-compliance-responsibilities", heading: "75. Legal / Compliance Responsibilities", body: [], list: [] },
      { id: "customer-responsibilities", heading: "76. Customer Responsibilities", body: [], list: [] },
      { id: "shared-responsibility", heading: "77. Shared Responsibility", body: [] },
      { id: "customer-business-continuity", heading: "78. Customer Business Continuity", body: [] },
      { id: "customer-data-export", heading: "79. Customer Data Export", body: [] },
      { id: "dr-evidence", heading: "80. Disaster Recovery Evidence", body: [], list: [] },
      { id: "testing-reports", heading: "81. Testing Reports", body: [] },
      { id: "no-disclosure-sensitive-details", heading: "82. No Disclosure of Sensitive Details", body: [] },
      { id: "sla", heading: "83. Service Level Agreement", body: [], list: [] },
      { id: "relationship-incident-response", heading: "84. Relationship to the Incident Response Policy", body: [] },
      { id: "relationship-security-trust", heading: "85. Relationship to the Security & Trust Policy", body: [] },
      { id: "relationship-data-retention", heading: "86. Relationship to the Data Retention & Deletion Policy", body: [] },
      { id: "relationship-enterprise-security-addendum", heading: "87. Relationship to the Enterprise Security Addendum", body: [] },
      { id: "dr-objectives", heading: "88. Disaster Recovery Objectives", body: [] },
      { id: "availability-disclaimer", heading: "89. Availability Disclaimer", body: [] },
      { id: "no-data-loss-guarantee", heading: "90. No Guarantee Against Data Loss", body: [] },
      { id: "force-majeure", heading: "91. Force Majeure", body: [] },
      { id: "security-incident", heading: "92. Security Incident", body: [] },
      { id: "regulatory-requirements", heading: "93. Regulatory Requirements", body: [] },
      { id: "record-keeping", heading: "94. Record Keeping", body: [] },
      { id: "confidentiality", heading: "95. Confidentiality", body: [] },
      { id: "policy-exceptions", heading: "96. Policy Exceptions", body: [], list: [] },
      { id: "policy-violations", heading: "97. Policy Violations", body: [], list: [] },
      { id: "continuous-improvement", heading: "98. Continuous Improvement", body: [], list: [] },
      { id: "annual-review", heading: "99. Annual Review", body: [] },
      { id: "document-record", heading: "100. Document Record", body: [], list: [] },
      { id: "approval", heading: "101. Approval", body: [], list: [] },
      { id: "legal-notice", heading: "102. Legal Notice", body: [] },
    ],
  },
  {
    slug: "enterprise-security-addendum",
    navLabel: "Enterprise Security Addendum",
    title: "Enterprise Security Addendum",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [], list: [] },
      { id: "scope", heading: "2. Scope", body: [], list: [] },
      { id: "definitions", heading: "3. Definitions", body: [] },
      { id: "security-framework", heading: "4. Security Framework", body: [], list: [] },
      { id: "isms-program", heading: "5. Information Security Management Program", body: [], list: [] },
      { id: "management-responsibility", heading: "6. Management Responsibility", body: [], list: [] },
      { id: "risk-assessment", heading: "7. Risk Assessment", body: [], list: [] },
      { id: "policy-management", heading: "8. Policy Management", body: [] },
      { id: "personnel-security", heading: "9. Personnel Security", body: [], list: [] },
      { id: "security-training", heading: "10. Security Training", body: [], list: [] },
      { id: "access-management", heading: "11. Access Management", body: [] },
      { id: "rbac", heading: "12. Role-Based Access Control", body: [] },
      { id: "mfa", heading: "13. Multi-Factor Authentication", body: [] },
      { id: "access-review", heading: "14. Access Review", body: [] },
      { id: "access-termination", heading: "15. Access Termination", body: [] },
      { id: "administrative-accounts", heading: "16. Administrative Accounts", body: [], list: [] },
      { id: "credential-protection", heading: "17. Credential Protection", body: [], list: [] },
      { id: "encryption-in-transit", heading: "18. Encryption in Transit", body: [] },
      { id: "encryption-at-rest", heading: "19. Encryption at Rest", body: [] },
      { id: "key-management", heading: "20. Encryption Key Management", body: [], list: [] },
      { id: "customer-isolation", heading: "21. Customer Isolation", body: [] },
      { id: "application-security", heading: "22. Application Security", body: [], list: [] },
      { id: "secure-development", heading: "23. Secure Software Development", body: [], list: [] },
      { id: "code-review", heading: "24. Code Review", body: [] },
      { id: "dependency-management", heading: "25. Dependency Management", body: [] },
      { id: "vulnerability-management", heading: "26. Vulnerability Management", body: [], list: [] },
      { id: "severity-classification", heading: "27. Severity Classification", body: [], list: [] },
      { id: "security-testing", heading: "28. Security Testing", body: [], list: [] },
      { id: "responsible-disclosure", heading: "29. Responsible Disclosure", body: [] },
      { id: "logging", heading: "30. Logging", body: [], list: [] },
      { id: "system-monitoring", heading: "31. System Monitoring", body: [], list: [] },
      { id: "log-protection", heading: "32. Log Protection", body: [], list: [] },
      { id: "incident-management", heading: "33. Incident Management", body: [], list: [] },
      { id: "incident-notification", heading: "34. Incident Notification", body: [], list: [] },
      { id: "incident-notice-content", heading: "35. Incident Notice Content", body: [], list: [] },
      { id: "incident-cooperation", heading: "36. Incident Cooperation", body: [], list: [] },
      { id: "incident-communication", heading: "37. Incident Communication", body: [] },
      { id: "business-continuity", heading: "38. Business Continuity", body: [] },
      { id: "disaster-recovery", heading: "39. Disaster Recovery", body: [], list: [] },
      { id: "backups", heading: "40. Backups", body: [], list: [] },
      { id: "recovery-testing", heading: "41. Recovery Testing", body: [] },
      { id: "change-management", heading: "42. Change Management", body: [], list: [] },
      { id: "infrastructure-security", heading: "43. Data Center and Infrastructure Security", body: [] },
      { id: "cloud-security", heading: "44. Cloud Security", body: [] },
      { id: "network-security", heading: "45. Network Security", body: [], list: [] },
      { id: "endpoint-security", heading: "46. Endpoint Security", body: [], list: [] },
      { id: "vendor-security", heading: "47. Vendor Security", body: [], list: [] },
      { id: "sub-processors", heading: "48. Sub-processors", body: [] },
      { id: "sub-processor-changes", heading: "49. Changing Sub-processors", body: [] },
      { id: "data-retention", heading: "50. Data Retention", body: [] },
      { id: "data-deletion", heading: "51. Data Deletion", body: [], list: [] },
      { id: "data-segregation", heading: "52. Customer Data Segregation", body: [] },
      { id: "isolation-testing", heading: "53. Isolation Testing", body: [] },
      { id: "privacy-by-design", heading: "54. Privacy by Design", body: [] },
      { id: "data-minimization", heading: "55. Data Minimization", body: [] },
      { id: "customer-responsibilities", heading: "56. Customer Security Responsibilities", body: [], list: [] },
      { id: "shared-responsibility", heading: "57. Shared Responsibility", body: [] },
      { id: "customer-user-management", heading: "58. Customer User Management", body: [], list: [] },
      { id: "api-security", heading: "59. API Security", body: [], list: [] },
      { id: "third-party-integrations", heading: "60. Third-Party Integrations", body: [], list: [] },
      { id: "security-audit", heading: "61. Security Audit", body: [] },
      { id: "security-documentation", heading: "62. Security Documentation", body: [], list: [] },
      { id: "independent-audit-reports", heading: "63. Independent Audit Reports", body: [] },
      { id: "customer-audit-requests", heading: "64. Customer Audit Requests", body: [], list: [] },
      { id: "audit-alternatives", heading: "65. Audit Alternatives", body: [], list: [] },
      { id: "audit-costs", heading: "66. Audit Costs", body: [] },
      { id: "audit-confidentiality", heading: "67. Protection of Information During Audit", body: [] },
      { id: "audit-non-interference", heading: "68. Audit Non-Interference", body: [], list: [] },
      { id: "customer-penetration-testing", heading: "69. Customer Penetration Testing", body: [] },
      { id: "vulnerability-disclosure", heading: "70. Vulnerability Disclosure", body: [] },
      { id: "physical-security", heading: "71. Physical Security", body: [] },
      { id: "communications-security", heading: "72. Communications Security", body: [] },
      { id: "log-management", heading: "73. Log Management", body: [], list: [] },
      { id: "access-monitoring", heading: "74. Access Monitoring", body: [], list: [] },
      { id: "no-absolute-security", heading: "75. No Guarantee of Absolute Security", body: [], list: [] },
      { id: "compliance", heading: "76. Compliance", body: [] },
      { id: "security-and-dpa", heading: "77. Security and the DPA", body: [] },
      { id: "security-and-tos", heading: "78. Security and the Terms of Service", body: [] },
      { id: "security-and-aup", heading: "79. Security and the AUP", body: [] },
      { id: "security-and-subprocessor-policy", heading: "80. Security and the Sub-processor Policy", body: [] },
      { id: "security-contact", heading: "81. Security Contact", body: [] },
      { id: "incident-information", heading: "82. Incident Information", body: [] },
      { id: "investigation-protection", heading: "83. Preventing Impact on Investigations", body: [], list: [] },
      { id: "cooperation-with-authorities", heading: "84. Cooperation with Competent Authorities", body: [] },
      { id: "government-requests", heading: "85. Government Requests", body: [] },
      { id: "data-location", heading: "86. Data Location", body: [] },
      { id: "material-security-changes", heading: "87. Material Security Changes", body: [], list: [] },
      { id: "security-updates", heading: "88. Security Updates", body: [] },
      { id: "business-continuity-plans", heading: "89. Business Continuity", body: [] },
      { id: "recovery-objectives", heading: "90. Recovery Objectives", body: [], list: [] },
      { id: "security-exceptions", heading: "91. Security Exceptions", body: [] },
      { id: "security-risk-acceptance", heading: "92. Security Risk Acceptance", body: [] },
      { id: "addendum-review", heading: "93. Addendum Review", body: [], list: [] },
      { id: "amendments", heading: "94. Amendments", body: [] },
      { id: "order-of-precedence", heading: "95. Order of Precedence", body: [], list: [] },
      { id: "liability", heading: "96. Liability", body: [] },
      { id: "no-independent-warranty", heading: "97. No Independent Warranty", body: [] },
      { id: "confidentiality", heading: "98. Confidentiality", body: [] },
      { id: "non-disclosure-sensitive-info", heading: "99. Non-Disclosure of Sensitive Information", body: [], list: [] },
      { id: "security-addenda", heading: "100. Security Addenda", body: [], list: [] },
      { id: "enterprise-customer-provisions", heading: "101. Enterprise Customer Provisions", body: [], list: [] },
      { id: "special-requirements", heading: "102. Special Requirements", body: [], list: [] },
      { id: "no-implied-modification", heading: "103. No Implied Modification", body: [] },
      { id: "customer-compliance-requirements", heading: "104. Compliance with Customer Requirements", body: [] },
      { id: "shared-responsibility-model", heading: "105. Shared Responsibility Model", body: [] },
      { id: "non-waiver", heading: "106. Non-Waiver", body: [] },
      { id: "severability", heading: "107. Severability", body: [] },
      { id: "governing-law", heading: "108. Governing Law", body: [] },
      { id: "dispute-resolution", heading: "109. Dispute Resolution", body: [] },
      { id: "entire-agreement", heading: "110. Entire Agreement", body: [] },
      { id: "document-record", heading: "111. Document Record", body: [], list: [] },
      { id: "signature-and-acceptance", heading: "112. Signature and Acceptance", body: [], list: [] },
      { id: "legal-notice", heading: "113. Legal Notice", body: [] },
    ],
  },
  {
    slug: "data-transfer",
    navLabel: "International Data Transfer",
    title: "Data Transfer & International Data Transfer Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [], list: [] },
      { id: "scope", heading: "2. Scope", body: [], list: [] },
      { id: "data-definition", heading: "3. Definition of Data", body: [], list: [] },
      { id: "data-transfer-definition", heading: "4. Definition of Data Transfer", body: [], list: [] },
      { id: "international-data-transfer", heading: "5. International Data Transfer", body: [] },
      { id: "transfer-principles", heading: "6. Data Transfer Principles", body: [], list: [] },
      { id: "no-fixed-location-guarantee", heading: "7. No Guarantee of Fixed Data Location", body: [], list: [] },
      { id: "data-residency", heading: "8. Data Residency", body: [] },
      { id: "regional-hosting", heading: "9. Regional Hosting", body: [], list: [] },
      { id: "data-processing-locations", heading: "10. Data Processing Locations", body: [], list: [] },
      { id: "lawful-basis", heading: "11. Lawful Basis", body: [] },
      { id: "contractual-necessity", heading: "12. Contractual Necessity", body: [] },
      { id: "legal-obligations", heading: "13. Legal Obligations", body: [] },
      { id: "legitimate-interests", heading: "14. Legitimate Interests", body: [] },
      { id: "consent", heading: "15. Consent", body: [] },
      { id: "standard-contractual-clauses", heading: "16. Standard Contractual Clauses", body: [] },
      { id: "transfer-impact-assessment", heading: "17. Transfer Impact Assessment", body: [], list: [] },
      { id: "supplementary-measures", heading: "18. Supplementary Measures", body: [], list: [] },
      { id: "encryption-in-transit", heading: "19. Encryption in Transit", body: [] },
      { id: "encryption-at-rest", heading: "20. Encryption at Rest", body: [] },
      { id: "access-control", heading: "21. Access Control", body: [] },
      { id: "authentication", heading: "22. Authentication", body: [] },
      { id: "logging", heading: "23. Logging", body: [] },
      { id: "monitoring", heading: "24. Monitoring", body: [] },
      { id: "sub-processors", heading: "25. Sub-processors", body: [] },
      { id: "international-sub-processors", heading: "26. International Sub-processors", body: [] },
      { id: "sub-processor-due-diligence", heading: "27. Sub-processor Due Diligence", body: [], list: [] },
      { id: "contractual-protection", heading: "28. Contractual Protection", body: [], list: [] },
      { id: "sub-processor-list", heading: "29. Sub-processor List", body: [] },
      { id: "changes-to-sub-processors", heading: "30. Changes to Sub-processors", body: [] },
      { id: "customer-objection", heading: "31. Customer Objection", body: [] },
      { id: "government-requests", heading: "32. Government Requests", body: [] },
      { id: "legal-review-of-requests", heading: "33. Legal Review of Requests", body: [], list: [] },
      { id: "data-minimization-government-requests", heading: "34. Data Minimization for Government Requests", body: [] },
      { id: "customer-notification", heading: "35. Customer Notification", body: [] },
      { id: "emergency-disclosure", heading: "36. Emergency Disclosure", body: [] },
      { id: "international-law-enforcement", heading: "37. International Law Enforcement", body: [] },
      { id: "data-transfer-to-affiliates", heading: "38. Data Transfer to Affiliates", body: [] },
      { id: "internal-access-across-borders", heading: "39. Internal Access Across Borders", body: [], list: [] },
      { id: "customer-support", heading: "40. Customer Support", body: [], list: [] },
      { id: "remote-access", heading: "41. Remote Access", body: [] },
      { id: "data-export", heading: "42. Data Export", body: [] },
      { id: "customer-initiated-transfers", heading: "43. Customer-Initiated Transfers", body: [], list: [] },
      { id: "third-party-integrations", heading: "44. Third-Party Integrations", body: [] },
      { id: "apis", heading: "45. APIs", body: [] },
      { id: "data-in-transit", heading: "46. Data in Transit", body: [] },
      { id: "data-at-rest", heading: "47. Data at Rest", body: [] },
      { id: "backup-transfers", heading: "48. Backup Transfers", body: [], list: [] },
      { id: "disaster-recovery-transfers", heading: "49. Disaster Recovery Transfers", body: [] },
      { id: "data-replication", heading: "50. Data Replication", body: [], list: [] },
      { id: "data-residency-exceptions", heading: "51. Data Residency Exceptions", body: [], list: [] },
      { id: "sensitive-data", heading: "52. Sensitive Data", body: [] },
      { id: "special-categories", heading: "53. Special Categories", body: [] },
      { id: "customer-responsibility", heading: "54. Customer Responsibility", body: [], list: [] },
      { id: "controller-processor-roles", heading: "55. Controller / Processor Roles", body: [], list: [] },
      { id: "data-processing-agreement", heading: "56. Data Processing Agreement", body: [] },
      { id: "priority-of-dpa", heading: "57. Priority of DPA", body: [] },
      { id: "gdpr", heading: "58. GDPR", body: [] },
      { id: "uk-gdpr", heading: "59. UK GDPR", body: [] },
      { id: "other-data-protection-laws", heading: "60. Other Data Protection Laws", body: [], list: [] },
      { id: "cross-border-compliance-assessment", heading: "61. Cross-Border Compliance Assessment", body: [], list: [] },
      { id: "transfer-mechanism", heading: "62. Transfer Mechanism", body: [], list: [] },
      { id: "adequacy-decisions", heading: "63. Adequacy Decisions", body: [] },
      { id: "scc-implementation", heading: "64. Standard Contractual Clauses", body: [] },
      { id: "supplementary-security-measures", heading: "65. Supplementary Security Measures", body: [] },
      { id: "transfer-risk", heading: "66. Transfer Risk", body: [], list: [] },
      { id: "risk-based-approach", heading: "67. Risk-Based Approach", body: [] },
      { id: "data-minimization", heading: "68. Data Minimization", body: [] },
      { id: "purpose-limitation", heading: "69. Purpose Limitation", body: [] },
      { id: "retention", heading: "70. Retention", body: [] },
      { id: "deletion", heading: "71. Deletion", body: [] },
      { id: "international-deletion", heading: "72. International Deletion", body: [], list: [] },
      { id: "backup-limitations", heading: "73. Backup Limitations", body: [] },
      { id: "security-incident", heading: "74. Security Incident", body: [] },
      { id: "breach-notification", heading: "75. Breach Notification", body: [] },
      { id: "international-incident-coordination", heading: "76. International Incident Coordination", body: [] },
      { id: "documentation", heading: "77. Documentation", body: [] },
      { id: "records-of-processing", heading: "78. Records of Processing", body: [] },
      { id: "audits", heading: "79. Audits", body: [] },
      { id: "audit-limitations", heading: "80. Audit Limitations", body: [], list: [] },
      { id: "security-certifications", heading: "81. Security Certifications", body: [] },
      { id: "transparency", heading: "82. Transparency", body: [], list: [] },
      { id: "infrastructure-changes", heading: "83. Infrastructure Changes", body: [], list: [] },
      { id: "customer-notice", heading: "84. Customer Notice", body: [] },
      { id: "objection-rights", heading: "85. Objection Rights", body: [] },
      { id: "international-employee-access", heading: "86. International Employee Access", body: [], list: [] },
      { id: "least-privilege", heading: "87. Least Privilege", body: [] },
      { id: "confidentiality", heading: "88. Confidentiality", body: [] },
      { id: "personnel-security", heading: "89. Personnel Security", body: [] },
      { id: "encryption-keys", heading: "90. Encryption Keys", body: [] },
      { id: "data-transfer-security", heading: "91. Data Transfer Security", body: [] },
      { id: "unauthorized-transfer", heading: "92. Unauthorized Transfer", body: [] },
      { id: "customer-configuration", heading: "93. Customer Configuration", body: [], list: [] },
      { id: "international-customers", heading: "94. International Customers", body: [] },
      { id: "restricted-jurisdictions", heading: "95. Restricted Jurisdictions", body: [], list: [] },
      { id: "sanctions-and-export-controls", heading: "96. Sanctions and Export Controls", body: [] },
      { id: "no-circumvention", heading: "97. No Circumvention", body: [], list: [] },
      { id: "policy-changes", heading: "98. Policy Changes", body: [], list: [] },
      { id: "effective-version", heading: "99. Effective Version", body: [] },
      { id: "relationship-with-other-documents", heading: "100. Relationship with Other Documents", body: [], list: [] },
      { id: "order-of-precedence", heading: "101. Order of Precedence", body: [], list: [] },
      { id: "legal-disclaimer", heading: "102. Legal Disclaimer", body: [] },
      { id: "no-absolute-guarantee", heading: "103. No Absolute Guarantee", body: [] },
      { id: "no-absolute-data-residency-guarantee", heading: "104. No Absolute Data Residency Guarantee", body: [] },
      { id: "legal-compliance", heading: "105. Legal Compliance", body: [] },
      { id: "severability", heading: "106. Severability", body: [] },
      { id: "no-waiver", heading: "107. No Waiver", body: [] },
      { id: "contact", heading: "108. Contact", body: [] },
      { id: "document-record", heading: "109. Document Record", body: [], list: [] },
      { id: "document-approval", heading: "110. Document Approval", body: [], list: [] },
      { id: "legal-notice", heading: "111. Legal Notice", body: [] },
    ],
  },
  {
    slug: "sub-processor-policy",
    navLabel: "Sub-processor Policy",
    title: "Sub-processor Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose", body: [], list: [] },
      { id: "definitions", heading: "2. Definitions", body: [] },
      { id: "scope", heading: "3. Scope", body: [], list: [] },
      { id: "basic-principle", heading: "4. Basic Principle", body: [] },
      { id: "selection", heading: "5. Selection of Sub-processors", body: [], list: [] },
      { id: "contractual-requirements", heading: "6. Contractual Requirements", body: [], list: [] },
      { id: "sub-processor-list", heading: "7. List of Sub-processors", body: [], list: [] },
      { id: "adding-replacing", heading: "8. Adding or Replacing Sub-processors", body: [], list: [] },
      { id: "notification-of-changes", heading: "9. Notification of Changes", body: [], list: [] },
      { id: "right-to-object", heading: "10. Right to Object", body: [] },
      { id: "handling-objections", heading: "11. Handling Customer Objections", body: [], list: [] },
      { id: "unresolved-objection", heading: "12. If the Objection Cannot Be Resolved", body: [] },
      { id: "security-data-protection", heading: "13. Security and Data Protection", body: [], list: [] },
      { id: "confidentiality", heading: "14. Confidentiality", body: [] },
      { id: "security-incidents", heading: "15. Security Incidents", body: [], list: [] },
      { id: "data-subject-requests", heading: "16. Data Subject Requests", body: [] },
      { id: "international-transfers", heading: "17. International Data Transfers", body: [], list: [] },
      { id: "government-legal-orders", heading: "18. Government and Legal Orders", body: [], list: [] },
      { id: "cloud-infrastructure", heading: "19. Cloud Infrastructure Services", body: [], list: [] },
      { id: "ai-providers", heading: "20. AI Providers", body: [], list: [] },
      { id: "payment-services", heading: "21. Payment Services", body: [] },
      { id: "support-providers", heading: "22. Support Service Providers", body: [], list: [] },
      { id: "independent-processing", heading: "23. Independent Processing by Service Provider", body: [], list: [] },
      { id: "no-sale-of-data", heading: "24. No Sale of Customer Data", body: [] },
      { id: "analytics-use", heading: "25. Use of Data for Analytics Purposes", body: [], list: [] },
      { id: "retention-deletion", heading: "26. Data Retention and Deletion", body: [] },
      { id: "monitoring-reassessment", heading: "27. Monitoring and Reassessment", body: [], list: [] },
      { id: "audit-verification", heading: "28. Audit and Verification", body: [], list: [] },
      { id: "zynreach-responsibility", heading: "29. ZynReach's Responsibility", body: [] },
      { id: "no-additional-rights", heading: "30. No Additional Rights Granted", body: [], list: [] },
      { id: "amendments", heading: "31. Amendments to This Policy", body: [], list: [] },
      { id: "dpa-relationship", heading: "32. Relationship with the Data Processing Agreement", body: [] },
      { id: "governing-law", heading: "33. Governing Law and Jurisdiction", body: [] },
      { id: "contact", heading: "34. Contact", body: [], list: [] },
      { id: "acknowledgement", heading: "35. Acknowledgement", body: [] },
      { id: "document-record", heading: "36. Document Record", body: [], list: [] },
      { id: "legal-notice", heading: "37. Legal Notice", body: [] },
    ],
  },
  {
    slug: "security-documentation-request",
    navLabel: "Request Security Documentation",
    title: "Security & Compliance Documentation Request Policy",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of This Document", body: [], list: [] },
      { id: "scope", heading: "2. Scope of Application", body: [], list: [] },
      { id: "document-tiers", heading: "3. Nature of Security & Compliance Documents", body: [], list: [] },
      { id: "non-disclosed-information", heading: "4. Information ZynReach Is Not Obligated to Disclose", body: [], list: [] },
      { id: "no-automatic-disclosure", heading: "5. Security Documents Are Not Automatically Disclosed", body: [], list: [] },
      { id: "identity-verification", heading: "6. Verifying the Requester's Identity", body: [], list: [] },
      { id: "business-email", heading: "7. Business/Professional Email", body: [] },
      { id: "nda", heading: "8. Non-Disclosure Agreement (NDA)", body: [], list: [] },
      { id: "use-of-documents", heading: "9. Use of Documents", body: [], list: [] },
      { id: "republication-prohibition", heading: "10. Prohibition on Republication", body: [], list: [] },
      { id: "third-party-documents", heading: "11. Third-Party-Issued Documents", body: [], list: [] },
      { id: "certifications-frameworks", heading: "12. Certifications, Frameworks & Standards", body: [], list: [] },
      { id: "not-legal-advice", heading: "13. Documents Do Not Constitute Legal Advice", body: [], list: [] },
      { id: "personal-data-protection", heading: "14. Protection of Personal Data During the Request Process", body: [], list: [] },
      { id: "customer-data-processing", heading: "15. Processing of Customer Data", body: [] },
      { id: "sub-processors", heading: "16. Sub-processors", body: [], list: [] },
      { id: "international-transfer", heading: "17. International Data Transfer", body: [] },
      { id: "incident-management", heading: "18. Security Incident Management", body: [], list: [] },
      { id: "ongoing-security", heading: "19. Security as an Ongoing Process", body: [], list: [] },
      { id: "backup-recovery", heading: "20. Backup & Recovery", body: [] },
      { id: "customer-obligations", heading: "21. Customer Obligations", body: [], list: [] },
      { id: "not-a-substitute", heading: "22. ZynReach Is Not a Substitute for Customer Security Responsibilities", body: [], list: [] },
      { id: "review-team-obligations", heading: "23. Obligations of the Customer's Review Team", body: [], list: [] },
      { id: "offensive-testing-prohibition", heading: "24. Prohibition on Unauthorized Offensive Testing", body: [], list: [] },
      { id: "request-procedure", heading: "25. Document Request Procedure", body: [], list: [] },
      { id: "processing-time", heading: "26. Request Processing Time", body: [], list: [] },
      { id: "document-accuracy", heading: "27. Document Accuracy & Currency", body: [] },
      { id: "program-changes", heading: "28. Changes to the Security Program", body: [], list: [] },
      { id: "no-additional-guarantees", heading: "29. No Additional Guarantees Created", body: [] },
      { id: "document-conflicts", heading: "30. Conflicts Between Documents", body: [], list: [] },
      { id: "intellectual-property", heading: "31. Intellectual Property Rights", body: [], list: [] },
      { id: "leaked-documents", heading: "32. Notification of Leaked or Lost Documents", body: [], list: [] },
      { id: "amend-withdraw", heading: "33. ZynReach's Right to Amend or Withdraw Documents", body: [], list: [] },
      { id: "no-absolute-guarantee", heading: "34. No Absolute Security Guarantee", body: [] },
      { id: "governing-law", heading: "35. Governing Law & Jurisdiction", body: [] },
      { id: "contact-acknowledgment", heading: "36. Contacting the Security & Compliance Team & Requester Acknowledgment", body: [], list: [] },
      { id: "disclaimer", heading: "37. Disclaimer", body: [] },
    ],
  },
  {
    slug: "cookies",
    navLabel: "Cookie Policy",
    title: "Cookie Policy",
    effectiveDate: "2026-08-01",
    version: "1.0",
    sections: [
      { id: "what-are-cookies", heading: "1. What Are Cookies", body: ["Cookies are small text files stored on your device that help websites function and remember preferences."] },
      { id: "types-of-cookies", heading: "2. Types of Cookies We Use", body: ["Essential — required for core site functionality; cannot be disabled.", "Analytics — help us understand site usage; only active with your consent.", "Advertising — support marketing measurement; only active with your consent.", "Functional — remember preferences like language; only active with your consent."] },
      { id: "managing-preferences", heading: "3. Managing Your Preferences", body: ["You can accept, reject, or customize non-essential cookies via the cookie banner shown on your first visit, or by clearing your browser's stored consent to see it again."] },
      { id: "third-party-cookies", heading: "4. Third-Party Cookies", body: ["Some cookies are set by third-party analytics and advertising partners. Their use is governed by their own privacy policies."] },
      { id: "changes", heading: "5. Changes to This Policy", body: ["We may update this policy periodically; the effective date above reflects the latest revision."] },
      { id: "contact", heading: "6. Contact Us", body: ["Questions about cookies can be sent to privacy@zynreach.com."] },
    ],
  },
  {
    slug: "dpa",
    navLabel: "Data Processing Agreement",
    title: "Data Processing Agreement",
    effectiveDate: "2026-08-31",
    version: "1.0",
    sections: [
      { id: "purpose", heading: "1. Purpose of the Agreement", body: [], list: [] },
      { id: "scope", heading: "2. Scope of the Agreement", body: [], list: [] },
      { id: "definitions", heading: "3. Definitions", body: [] },
      { id: "agreement-relationship", heading: "4. Relationship Between the Agreements", body: [], list: [] },
      { id: "roles-of-parties", heading: "5. Roles of the Parties", body: [] },
      { id: "customer-obligations", heading: "6. Customer Obligations", body: [], list: [] },
      { id: "customer-responsibility-instructions", heading: "7. Customer's Responsibility for Processing Instructions", body: [], list: [] },
      { id: "customer-instructions", heading: "8. Customer Instructions", body: [], list: [] },
      { id: "unlawful-instructions", heading: "9. Unlawful Instructions", body: [], list: [] },
      { id: "limits-on-data-use", heading: "10. Limits on Use of Data", body: [], list: [] },
      { id: "aggregated-anonymized-data", heading: "11. Aggregated and Anonymized Data", body: [], list: [] },
      { id: "categories-of-personal-data", heading: "12. Categories of Personal Data", body: [], list: [] },
      { id: "categories-of-data-subjects", heading: "13. Categories of Data Subjects", body: [], list: [] },
      { id: "sensitive-data", heading: "14. Sensitive Data", body: [], list: [] },
      { id: "childrens-data", heading: "15. Children's Data", body: [], list: [] },
      { id: "duration-of-processing", heading: "16. Duration of Processing", body: [], list: [] },
      { id: "confidentiality", heading: "17. Confidentiality", body: [], list: [] },
      { id: "information-security", heading: "18. Information Security", body: [], list: [] },
      { id: "no-absolute-security-guarantee", heading: "19. No Guarantee of Absolute Security", body: [], list: [] },
      { id: "access-control", heading: "20. Access Control", body: [] },
      { id: "zynreach-personnel", heading: "21. ZynReach Personnel", body: [], list: [] },
      { id: "sub-processors", heading: "22. Sub-processors", body: [], list: [] },
      { id: "notice-of-sub-processors", heading: "23. Notice of Sub-processors", body: [] },
      { id: "customer-objection-sub-processor", heading: "24. Customer Objection to Sub-processor", body: [], list: [] },
      { id: "data-subject-requests", heading: "25. Data Subject Requests", body: [], list: [] },
      { id: "requests-direct-to-zynreach", heading: "26. Requests Received Directly by ZynReach", body: [], list: [] },
      { id: "assistance-with-compliance", heading: "27. Assistance with Compliance", body: [], list: [] },
      { id: "dpia", heading: "28. Data Protection Impact Assessment", body: [], list: [] },
      { id: "regulatory-advice", heading: "29. Regulatory Advice", body: [], list: [] },
      { id: "breach-notification", heading: "30. Notification of Data Breach", body: [], list: [] },
      { id: "non-reporting-immaterial-alerts", heading: "31. Non-Reporting of Immaterial Alerts", body: [], list: [] },
      { id: "customer-obligations-post-incident", heading: "32. Customer Obligations Following an Incident", body: [], list: [] },
      { id: "government-requests", heading: "33. Government Requests", body: [], list: [] },
      { id: "government-transparency", heading: "34. Government Transparency", body: [], list: [] },
      { id: "international-transfers", heading: "35. International Transfers", body: [], list: [] },
      { id: "standard-contractual-clauses", heading: "36. Standard Contractual Clauses", body: [] },
      { id: "transfer-impact-assessment", heading: "37. Transfer Impact Assessment", body: [] },
      { id: "data-storage-location", heading: "38. Data Storage Location", body: [] },
      { id: "audit-rights", heading: "39. Audit Rights", body: [], list: [] },
      { id: "audit-limits", heading: "40. Limits on Audits", body: [], list: [] },
      { id: "third-party-audits", heading: "41. Third-Party Audits", body: [], list: [] },
      { id: "on-site-audit", heading: "42. On-Site Audit", body: [], list: [] },
      { id: "record-retention", heading: "43. Record Retention", body: [], list: [] },
      { id: "return-of-data", heading: "44. Return of Data", body: [], list: [] },
      { id: "deletion-of-data", heading: "45. Deletion of Data", body: [], list: [] },
      { id: "backups", heading: "46. Backups", body: [], list: [] },
      { id: "early-deletion-request", heading: "47. Early Deletion Request", body: [], list: [] },
      { id: "ownership", heading: "48. Ownership", body: [] },
      { id: "zynreach-intellectual-property", heading: "49. ZynReach's Intellectual Property", body: [], list: [] },
      { id: "data-from-service-operation", heading: "50. Data Arising from Service Operation", body: [], list: [] },
      { id: "artificial-intelligence", heading: "51. Artificial Intelligence", body: [], list: [] },
      { id: "ai-sub-processors", heading: "52. AI Sub-processors", body: [], list: [] },
      { id: "no-training-general-models", heading: "53. No Training of General Models with Customer Data", body: [] },
      { id: "third-party-integrations", heading: "54. Third-Party Integrations", body: [], list: [] },
      { id: "apis", heading: "55. APIs", body: [], list: [] },
      { id: "customer-security-obligations", heading: "56. Customer's Security Obligations", body: [], list: [] },
      { id: "customer-responsibility-for-users", heading: "57. Customer's Responsibility for Users", body: [], list: [] },
      { id: "cooperation", heading: "58. Cooperation", body: [], list: [] },
      { id: "fees", heading: "59. Fees", body: [], list: [] },
      { id: "indemnification", heading: "60. Indemnification", body: [] },
      { id: "limitation-of-liability", heading: "61. Limitation of Liability", body: [], list: [] },
      { id: "force-majeure", heading: "62. Force Majeure", body: [], list: [] },
      { id: "term-of-agreement", heading: "63. Term of the Agreement", body: [], list: [] },
      { id: "termination", heading: "64. Termination", body: [], list: [] },
      { id: "surviving-provisions", heading: "65. Surviving Provisions", body: [], list: [] },
      { id: "no-assignment", heading: "66. No Assignment", body: [], list: [] },
      { id: "severability", heading: "67. Severability", body: [], list: [] },
      { id: "no-waiver", heading: "68. No Waiver of Rights", body: [] },
      { id: "governing-law", heading: "69. Governing Law", body: [] },
      { id: "local-law-compliance", heading: "70. Compliance with Local Laws", body: [] },
      { id: "gdpr", heading: "71. GDPR", body: [], list: [] },
      { id: "processor-obligations", heading: "72. Processor Obligations", body: [], list: [] },
      { id: "controller-obligations", heading: "73. Controller Obligations", body: [], list: [] },
      { id: "mandatory-law-priority", heading: "74. Priority of Mandatory Law", body: [] },
      { id: "amendments", heading: "75. Amendments", body: [], list: [] },
      { id: "material-amendments", heading: "76. Material Amendments", body: [] },
      { id: "notices", heading: "77. Notices", body: [], list: [] },
      { id: "entire-agreement", heading: "78. Entire Agreement", body: [], list: [] },
      { id: "electronic-signature", heading: "79. Electronic Signature", body: [] },
      { id: "annex-a-data-processing-details", heading: "80. Annex A — Data Processing Details", body: [], list: [] },
      { id: "annex-b-categories-personal-data", heading: "81. Annex B — Categories of Personal Data", body: [], list: [] },
      { id: "annex-c-categories-data-subjects", heading: "82. Annex C — Categories of Data Subjects", body: [], list: [] },
      { id: "annex-d-security-measures", heading: "83. Annex D — Security Measures", body: [], list: [] },
      { id: "annex-e-sub-processor-framework", heading: "84. Annex E — Sub-processor Framework", body: [], list: [] },
      { id: "annex-f-data-breach-procedure", heading: "85. Annex F — Data Breach Procedure", body: [], list: [] },
      { id: "annex-g-data-subject-request-procedure", heading: "86. Annex G — Data Subject Request Procedure", body: [], list: [] },
      { id: "annex-h-data-return-deletion", heading: "87. Annex H — Data Return & Deletion", body: [], list: [] },
      { id: "annex-i-international-transfer", heading: "88. Annex I — International Transfer", body: [], list: [] },
      { id: "annex-j-ai-processing", heading: "89. Annex J — AI Processing", body: [], list: [] },
      { id: "annex-k-enterprise-security-compliance", heading: "90. Annex K — Enterprise Security & Compliance Evidence", body: [], list: [] },
      { id: "annex-l-order-of-precedence", heading: "91. Annex L — Order of Precedence", body: [], list: [] },
      { id: "execution-signatures", heading: "92. Execution & Signatures", body: [], list: [] },
    ],
  },
];

export function getLegalPage(slug: string) {
  return legalPages.find((page) => page.slug === slug);
}
