import type { ProductExperiencePage } from "@/types/content";

/**
 * Skeletons for the 7 rich "Product Experience" platform pages —
 * `id`/`kind` only, in canonical order. Translated content lives in
 * messages/*.json under `productPages.<slug>.sections`, matched to this
 * array by index (same split as `companySizeSolutionPages`). `sections[0]`
 * on every page is the "hero product visualization" mockup (kind
 * `kpiGrid`) that immediately follows the hero in each source spec.
 */
export const productExperiencePages: ProductExperiencePage[] = [
  {
    slug: "marketing-automation",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "hero-panel", kind: "kpiGrid" },
      { id: "one-automation-engine", kind: "beforeAfter" },
      { id: "campaign-builder", kind: "cardGrid" },
      { id: "behavioral-automation", kind: "arrowChain" },
      { id: "customer-journey-builder", kind: "arrowChain" },
      { id: "smart-segmentation", kind: "prose" },
      { id: "dynamic-audience", kind: "kpiGrid" },
      { id: "ai-lead-scoring", kind: "kpiGrid" },
      { id: "ai-marketing-intelligence", kind: "cardGrid" },
      { id: "personalized-journeys", kind: "cardGrid" },
      { id: "multichannel-automation", kind: "cardGrid" },
      { id: "channel-orchestration", kind: "arrowChain" },
      { id: "lead-nurturing", kind: "cardGrid" },
      { id: "automated-lead-handoff", kind: "arrowChain" },
      { id: "marketing-crm", kind: "arrowChain" },
      { id: "marketing-sales-pipeline", kind: "kpiGrid" },
      { id: "attribution", kind: "cardGrid" },
      { id: "campaign-analytics", kind: "prose" },
      { id: "funnel-analytics", kind: "kpiGrid" },
      { id: "journey-performance", kind: "prose" },
      { id: "automation-monitoring", kind: "kpiGrid" },
      { id: "campaign-templates", kind: "cardGrid" },
      { id: "ai-content-assistance", kind: "prose" },
      { id: "real-time-triggers", kind: "prose" },
      { id: "automation-example", kind: "arrowChain" },
      { id: "marketing-team-dashboard", kind: "prose" },
      { id: "governance", kind: "prose" },
      { id: "compliance", kind: "prose" },
      { id: "integrations", kind: "prose" },
      { id: "manual-vs-zynreach", kind: "comparisonTable" },
      { id: "agency-use-case", kind: "prose" },
      { id: "platform-relationship", kind: "arrowChain" },
    ],
  },
  {
    slug: "lead-generation",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "hero-panel", kind: "kpiGrid" },
      { id: "capture-everywhere", kind: "cardGrid" },
      { id: "smart-capture", kind: "cardGrid" },
      { id: "lead-intelligence", kind: "kpiGrid" },
      { id: "automatic-enrichment", kind: "beforeAfter" },
      { id: "ai-qualification", kind: "kpiGrid" },
      { id: "lead-scoring", kind: "kpiGrid" },
      { id: "instant-routing", kind: "beforeAfter" },
      { id: "routing-rules", kind: "cardGrid" },
      { id: "speed-to-lead", kind: "arrowChain" },
      { id: "automated-follow-up", kind: "arrowChain" },
      { id: "lead-lifecycle", kind: "arrowChain" },
      { id: "lead-generation-crm", kind: "arrowChain" },
      { id: "lead-generation-marketing", kind: "arrowChain" },
      { id: "lead-source-intelligence", kind: "kpiGrid" },
      { id: "lead-quality-analytics", kind: "prose" },
      { id: "ai-recommendations", kind: "cardGrid" },
      { id: "before-after", kind: "beforeAfter" },
      { id: "use-cases", kind: "cardGrid" },
      { id: "enterprise-controls", kind: "prose" },
      { id: "integrations", kind: "prose" },
      { id: "platform-relationship", kind: "arrowChain" },
    ],
  },
  {
    slug: "sales-pipeline",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "hero-panel", kind: "kpiGrid" },
      { id: "one-live-pipeline", kind: "prose" },
      { id: "deal-360", kind: "cardGrid" },
      { id: "pipeline-stages", kind: "cardGrid" },
      { id: "drag-and-drop", kind: "arrowChain" },
      { id: "next-best-action", kind: "kpiGrid" },
      { id: "deal-aging-intelligence", kind: "kpiGrid" },
      { id: "deal-health-score", kind: "kpiGrid" },
      { id: "ai-deal-intelligence", kind: "cardGrid" },
      { id: "pipeline-forecast", kind: "cardGrid" },
      { id: "conversion-analytics", kind: "arrowChain" },
      { id: "pipeline-bottlenecks", kind: "kpiGrid" },
      { id: "sales-rep-performance", kind: "prose" },
      { id: "tasks-followups", kind: "prose" },
      { id: "sales-automation", kind: "arrowChain" },
      { id: "lead-to-pipeline", kind: "arrowChain" },
      { id: "crm-to-pipeline", kind: "arrowChain" },
      { id: "pipeline-analytics", kind: "prose" },
      { id: "multi-pipeline", kind: "cardGrid" },
      { id: "team-territory", kind: "prose" },
      { id: "permissions", kind: "prose" },
      { id: "pipeline-comparison", kind: "comparisonTable" },
      { id: "how-it-works", kind: "timeline" },
      { id: "product-experience", kind: "kpiGrid" },
      { id: "platform-relationship", kind: "arrowChain" },
    ],
  },
  {
    slug: "contact-360",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "hero-panel", kind: "kpiGrid" },
      { id: "contact-navigation", kind: "prose" },
      { id: "overview", kind: "prose" },
      { id: "unified-timeline", kind: "arrowChain" },
      { id: "timeline-filters-search", kind: "prose" },
      { id: "contact-identity", kind: "cardGrid" },
      { id: "custom-fields", kind: "prose" },
      { id: "contact-relationships", kind: "cardGrid" },
      { id: "company-360", kind: "prose" },
      { id: "deals", kind: "kpiGrid" },
      { id: "multiple-deals", kind: "kpiGrid" },
      { id: "engagement", kind: "kpiGrid" },
      { id: "customer-health", kind: "kpiGrid" },
      { id: "customer-risk", kind: "prose" },
      { id: "ai-customer-insights", kind: "kpiGrid" },
      { id: "next-best-action", kind: "kpiGrid" },
      { id: "contact-score", kind: "kpiGrid" },
      { id: "communication-center", kind: "cardGrid" },
      { id: "communication-history", kind: "prose" },
      { id: "campaign-interactions", kind: "kpiGrid" },
      { id: "marketing-journey", kind: "kpiGrid" },
      { id: "lead-source-attribution", kind: "kpiGrid" },
      { id: "tasks", kind: "prose" },
      { id: "automation", kind: "prose" },
      { id: "support", kind: "kpiGrid" },
      { id: "documents", kind: "prose" },
      { id: "customer-revenue", kind: "kpiGrid" },
      { id: "customer-journey-lifecycle", kind: "arrowChain" },
      { id: "scattered-vs-contact360", kind: "comparisonTable" },
      { id: "before-after", kind: "beforeAfter" },
      { id: "team-context", kind: "cardGrid" },
      { id: "audit-trail", kind: "prose" },
      { id: "data-quality", kind: "kpiGrid" },
      { id: "duplicate-management", kind: "prose" },
      { id: "platform-relationship", kind: "arrowChain" },
    ],
  },
  {
    slug: "crm",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "hero-panel", kind: "kpiGrid" },
      { id: "crm-works-with-team", kind: "cardGrid" },
      { id: "contact-360-overview", kind: "prose" },
      { id: "contact-360-timeline", kind: "arrowChain" },
      { id: "pipeline-stages", kind: "arrowChain" },
      { id: "pipeline-tools", kind: "prose" },
      { id: "crm-intelligence", kind: "cardGrid" },
      { id: "ai-in-crm", kind: "cardGrid" },
      { id: "activities-flow", kind: "arrowChain" },
      { id: "my-day", kind: "kpiGrid" },
      { id: "automation", kind: "arrowChain" },
      { id: "crm-marketing-lifecycle", kind: "arrowChain" },
      { id: "crm-analytics", kind: "prose" },
      { id: "team-visibility", kind: "cardGrid" },
      { id: "permissions-security", kind: "prose" },
      { id: "comparison", kind: "comparisonTable" },
      { id: "how-it-works", kind: "timeline" },
    ],
  },
  {
    slug: "campaigns",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "hero-panel", kind: "kpiGrid" },
      { id: "campaigns-vs-automation", kind: "beforeAfter" },
      { id: "campaign-lifecycle", kind: "arrowChain" },
      { id: "campaign-builder", kind: "cardGrid" },
      { id: "campaign-objectives", kind: "cardGrid" },
      { id: "audience-builder", kind: "prose" },
      { id: "dynamic-audience", kind: "kpiGrid" },
      { id: "content-workspace", kind: "cardGrid" },
      { id: "multichannel-campaign", kind: "arrowChain" },
      { id: "channel-orchestration", kind: "arrowChain" },
      { id: "scheduling", kind: "prose" },
      { id: "campaign-status", kind: "prose" },
      { id: "campaign-dashboard", kind: "prose" },
      { id: "funnel", kind: "arrowChain" },
      { id: "performance-breakdown", kind: "cardGrid" },
      { id: "channel-comparison", kind: "kpiGrid" },
      { id: "attribution", kind: "cardGrid" },
      { id: "campaign-to-pipeline", kind: "arrowChain" },
      { id: "campaign-roi", kind: "prose" },
      { id: "campaign-comparison-table", kind: "kpiGrid" },
      { id: "campaign-intelligence", kind: "cardGrid" },
      { id: "ai-campaign-assistant", kind: "prose" },
      { id: "campaign-optimization", kind: "prose" },
      { id: "campaign-templates", kind: "cardGrid" },
      { id: "campaign-calendar", kind: "prose" },
      { id: "collaboration", kind: "prose" },
      { id: "approval-workflow", kind: "arrowChain" },
      { id: "governance", kind: "prose" },
      { id: "crm-integration", kind: "arrowChain" },
      { id: "automation-integration", kind: "arrowChain" },
      { id: "lead-generation-integration", kind: "arrowChain" },
      { id: "sales-integration", kind: "arrowChain" },
      { id: "comparison", kind: "comparisonTable" },
      { id: "how-it-works", kind: "timeline" },
      { id: "platform-relationship", kind: "arrowChain" },
    ],
  },
  {
    slug: "business-data",
    primaryCtaHref: "/trial",
    secondaryCtaHref: "/demo",
    sections: [
      { id: "hero-panel", kind: "kpiGrid" },
      { id: "positioning", kind: "arrowChain" },
      { id: "prospect-discovery", kind: "prose" },
      { id: "icp-builder", kind: "kpiGrid" },
      { id: "company-intelligence", kind: "prose" },
      { id: "contact-discovery", kind: "prose" },
      { id: "verified-data", kind: "kpiGrid" },
      { id: "data-enrichment", kind: "beforeAfter" },
      { id: "automatic-enrichment", kind: "arrowChain" },
      { id: "targeted-list-builder", kind: "prose" },
      { id: "smart-lists", kind: "kpiGrid" },
      { id: "list-management", kind: "prose" },
      { id: "data-segmentation", kind: "prose" },
      { id: "intent-data", kind: "kpiGrid" },
      { id: "buying-signals", kind: "cardGrid" },
      { id: "technology-intelligence", kind: "cardGrid" },
      { id: "market-intelligence", kind: "kpiGrid" },
      { id: "market-segmentation", kind: "arrowChain" },
      { id: "account-prioritization", kind: "kpiGrid" },
      { id: "duplicate-prevention", kind: "prose" },
      { id: "crm-sync", kind: "arrowChain" },
      { id: "lead-generation-integration", kind: "arrowChain" },
      { id: "campaign-integration", kind: "arrowChain" },
      { id: "sales-pipeline-integration", kind: "arrowChain" },
      { id: "contact-360-integration", kind: "arrowChain" },
      { id: "data-activation", kind: "prose" },
      { id: "bulk-actions", kind: "prose" },
      { id: "data-quality", kind: "kpiGrid" },
      { id: "source-transparency", kind: "prose" },
      { id: "saved-searches", kind: "kpiGrid" },
      { id: "alerts", kind: "prose" },
      { id: "data-to-intelligence", kind: "arrowChain" },
      { id: "data-to-revenue", kind: "arrowChain" },
      { id: "comparison-manual", kind: "comparisonTable" },
      { id: "comparison-provider", kind: "comparisonTable" },
      { id: "how-it-works", kind: "timeline" },
      { id: "ai-data-intelligence", kind: "cardGrid" },
      { id: "governance", kind: "prose" },
      { id: "agency-use-case", kind: "prose" },
      { id: "data-architecture", kind: "arrowChain" },
    ],
  },
];

export function getProductExperiencePage(slug: string) {
  return productExperiencePages.find((page) => page.slug === slug);
}
